### ISSUE TITLE
Fix Solr tests

### ISSUE THREAD

**Issue by sungam3r** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1020]
Found in #1016 

> [xUnit.net 00:00:02.25]     HealthChecks.SolR.Tests.Functional.solr_healthcheck_should.be_healthy_if_solr_is_available [FAIL]
  Failed HealthChecks.SolR.Tests.Functional.solr_healthcheck_should.be_healthy_if_solr_is_available [129 ms]
  Error Message:
   Expected the enum to be HttpStatusCode.OK {value: 200} because {"status":"Unhealthy","totalDuration":"00:00:00.0282171","entries":{"solr":{"data":{},"description":"\u003C?xml version=\u00221.0\u0022 encoding=\u0022UTF-8\u0022?\u003E\n\u003Cresponse\u003E\n\n\u003Clst name=\u0022error\u0022\u003E\n  \u003Clst name=\u0022metadata\u0022\u003E\n    \u003Cstr name=\u0022error-class\u0022\u003Eorg.apache.solr.core.SolrCoreInitializationException\u003C/str\u003E\n    \u003Cstr name=\u0022root-error-class\u0022\u003Ejava.nio.file.AccessDeniedException\u003C/str\u003E\n  \u003C/lst\u003E\n  \u003Cstr name=\u0022msg\u0022\u003ESolrCore \u0027solrcore\u0027 is not available due to init failure: java.nio.file.AccessDeniedException: /var/solr/data/solrcore/data/snapshot_metadata\u003C/str\u003E\n  \u003Cstr name=\u0022trace\u0022\u003Eorg.apache.solr.core.SolrCoreInitializationException: SolrCore \u0027solrcore\u0027 is not available due to init failure: java.nio.file.AccessDeniedException: /var/solr/data/solrcore/data/snapshot_metadata\n\tat org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:1781)\n\tat org.apache.solr.servlet.HttpSolrCall.init(HttpSolrCall.java:253)\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:538)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:419)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:351)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:505)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)\n\tat org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)\n\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: org.apache.solr.common.SolrException: java.nio.file.AccessDeniedException: /var/solr/data/solrcore/data/snapshot_metadata\n\tat org.apache.solr.core.SolrCore.\u0026lt;init\u0026gt;(SolrCore.java:1072)\n\tat org.apache.solr.core.SolrCore.\u0026lt;init\u0026gt;(SolrCore.java:901)\n\tat org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1292)\n\tat org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:788)\n\tat com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202)\n\tat java.base/java.util.concurrent.FutureTask.run(Unknown Source)\n\tat org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute(ExecutorUtil.java:210)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\t... 1 more\nCaused by: java.lang.IllegalStateException: java.nio.file.AccessDeniedException: /var/solr/data/solrcore/data/snapshot_metadata\n\tat org.apache.solr.core.SolrCore.initSnapshotMetaDataManager(SolrCore.java:540)\n\tat org.apache.solr.core.SolrCore.\u0026lt;init\u0026gt;(SolrCore.java:981)\n\t... 9 more\nCaused by: java.nio.file.AccessDeniedException: /var/solr/data/solrcore/data/snapshot_metadata\n\tat java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)\n\tat java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)\n\tat java.base/java.nio.file.Files.createDirectory(Unknown Source)\n\tat java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)\n\tat java.base/java.nio.file.Files.createDirectories(Unknown Source)\n\tat org.apache.lucene.store.FSDirectory.\u0026lt;init\u0026gt;(FSDirectory.java:156)\n\tat org.apache.lucene.store.MMapDirectory.\u0026lt;init\u0026gt;(MMapDirectory.java:159)\n\tat org.apache.lucene.store.MMapDirectory.\u0026lt;init\u0026gt;(MMapDirectory.java:112)\n\tat org.apache.lucene.store.FSDirectory.open(FSDirectory.java:196)\n\tat org.apache.solr.core.NRTCachingDirectoryFactory.create(NRTCachingDirectoryFactory.java:55)\n\tat org.apache.solr.core.CachingDirectoryFactory.get(CachingDirectoryFactory.java:347)\n\tat org.apache.solr.core.SolrCore.initSnapshotMetaDataManager(SolrCore.java:536)\n\t... 10 more\n\u003C/str\u003E\n  \u003Cint name=\u0022code\u0022\u003E500\u003C/int\u003E\n\u003C/lst\u003E\n\u003C/response\u003E\n","duration":"00:00:00.0281833","exception":"\u003C?xml version=\u00221.0\u0022 encoding=\u0022UTF-8\u0022?\u003E\n\u003Cresponse\u003E\n\n\u003Clst name=\u0022error\u0022\u003E\n  \u003Clst name=\u0022metadata\u0022\u003E\n    \u003Cstr name=\u0022error-class\u0022\u003Eorg.apache.solr.core.SolrCoreInitializationException\u003C/str\u003E\n    \u003Cstr name=\u0022root-error-class\u0022\u003Ejava.nio.file.AccessDeniedException\u003C/str\u003E\n  \u003C/lst\u003E\n  \u003Cstr name=\u0022msg\u0022\u003ESolrCore \u0027solrcore\u0027 is not available due to init failure: java.nio.file.AccessDeniedException: /var/solr/data/solrcore/data/snapshot_metadata\u003C/str\u003E\n  \u003Cstr name=\u0022trace\u0022\u003Eorg.apache.solr.core.SolrCoreInitializationException: SolrCore \u0027solrcore\u0027 is not available due to init failure: java.nio.file.AccessDeniedException: /var/solr/data/solrcore/data/snapshot_metadata\n\tat org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:1781)\n\tat org.apache.solr.servlet.HttpSolrCall.init(HttpSolrCall.java:253)\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:538)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:419)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:351)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:505)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)\n\tat org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)\n\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: org.apache.solr.common.SolrException: java.nio.file.AccessDeniedException: /var/solr/data/solrcore/data/snapshot_metadata\n\tat org.apache.solr.core.SolrCore.\u0026lt;init\u0026gt;(SolrCore.java:1072)\n\tat org.apache.solr.core.SolrCore.\u0026lt;init\u0026gt;(SolrCore.java:901)\n\tat org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1292)\n\tat org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:788)\n\tat com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202)\n\tat java.base/java.util.concurrent.FutureTask.run(Unknown Source)\n\tat org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute(ExecutorUtil.java:210)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\t... 1 more\nCaused by: java.lang.IllegalStateException: java.nio.file.AccessDeniedException: /var/solr/data/solrcore/data/snapshot_metadata\n\tat org.apache.solr.core.SolrCore.initSnapshotMetaDataManager(SolrCore.java:540)\n\tat org.apache.solr.core.SolrCore.\u0026lt;init\u0026gt;(SolrCore.java:981)\n\t... 9 more\nCaused by: java.nio.file.AccessDeniedException: /var/solr/data/solrcore/data/snapshot_metadata\n\tat java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)\n\tat java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)\n\tat java.base/java.nio.file.Files.createDirectory(Unknown Source)\n\tat java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)\n\tat java.base/java.nio.file.Files.createDirectories(Unknown Source)\n\tat org.apache.lucene.store.FSDirectory.\u0026lt;init\u0026gt;(FSDirectory.java:156)\n\tat org.apache.lucene.store.MMapDirectory.\u0026lt;init\u0026gt;(MMapDirectory.java:159)\n\tat org.apache.lucene.store.MMapDirectory.\u0026lt;init\u0026gt;(MMapDirectory.java:112)\n\tat org.apache.lucene.store.FSDirectory.open(FSDirectory.java:196)\n\tat org.apache.solr.core.NRTCachingDirectoryFactory.create(NRTCachingDirectoryFactory.java:55)\n\tat org.apache.solr.core.CachingDirectoryFactory.get(CachingDirectoryFactory.java:347)\n\tat org.apache.solr.core.SolrCore.initSnapshotMetaDataManager(SolrCore.java:536)\n\t... 10 more\n\u003C/str\u003E\n  \u003Cint name=\u0022code\u0022\u003E500\u003C/int\u003E\n\u003C/lst\u003E\n\u003C/response\u003E\n","status":"Unhealthy","tags":["solr"]}}}, but found HttpStatusCode.ServiceUnavailable {value: 503}.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at HealthChecks.SolR.Tests.Functional.solr_healthcheck_should.be_healthy_if_solr_is_available() in /_/test/HealthChecks.SolR.Tests/Functional/SolRHealthCheckTests.cs:line 35
--- End of stack trace from previous location ---

dotnet test command for Solr is commented now.

**Comment by sungam3r** [comment]
Ah, this is because commented services section.
