### ISSUE TITLE
Services returns 503 instead of unhealthy

### ISSUE THREAD

**Issue by PandaWood** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1047]
Please, fill the following sections to help us fix the issue

**What happened**:
Health service crashes/returns a 503 instead of a health check json response
The code works for other health checks and only does this when mongo is not running
Otherwise it reports and runs fine

**What you expected to happen**:
A JSON response saying "Unhealthy" for mongo check

**How to reproduce it (as minimally and precisely as possible)**:

**Source code sample**:
The code I'm using to generate the response
```endpoints.MapHealthChecks("health/ready", new HealthCheckOptions
{
	Predicate = (check) => check.Tags.Contains("ready"),
	ResponseWriter = async (context, report) =>
	{
		var result = JsonSerializer.Serialize(
			new
			{
				status = report.Status.ToString(),
				checks = report.Entries.Select(entry => new
				{
					name = entry.Key,
					status = entry.Value.Status.ToString(),
					exception = entry.Value.Exception?.Message ?? "na",
					duration = entry.Value.Duration.ToString()
				})
			}
		);
		context.Response.ContentType = MediaTypeNames.Application.Json;
		await context.Response.WriteAsync(result);
	}
});
```

**Anything else we need to know?**:
The exception that happens every time for me
fail: Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService[103]
      Health check mongodb with status Unhealthy completed after 3020.4567ms with message '(null)'
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
         at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedAsync(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Clusters.Cluster.SelectServerAsync(IServerSelector selector, CancellationToken cancellationToken)
         at MongoDB.Driver.MongoClient.AreSessionsSupportedAfterServerSelectionAsync(CancellationToken cancellationToken)
         at MongoDB.Driver.MongoClient.AreSessionsSupportedAsync(CancellationToken cancellationToken)
         at MongoDB.Driver.MongoClient.StartImplicitSessionAsync(CancellationToken cancellationToken)
         at MongoDB.Driver.MongoClient.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
         at HealthChecks.MongoDb.MongoDbHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken) in /_/src/HealthChecks.MongoDb/MongoDbHealthCheck.cs:line 47
Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Error: Health check mongodb with status Unhealthy completed after 3020.4567ms with message '(null)'

**Environment**:

- .NET Core version 5
- Healthchecks version latest
- Operative system: Windows
- Others:

**Comment by PandaWood** [comment]
Apologies, it looks like if I remove the `await` in the `ResponseWriter` method, this goes away.
I'm not sure why yet, but it does make some sense and therefore probably unrelated to the mongo health checker
