### ISSUE TITLE
BLAZOR Deployment

### ISSUE THREAD

**Issue by ahmedshahjr** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1205]
Please, fill the following sections to help us fix the issue

**deployed healthcheck ui with blazor server its thorwing error on live but not on local**:

** 2022-05-28 08:41:40.7276 107 ERROR  GetHealthReport threw an exception when trying to get report from /health configured with name PollManager. 
 System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (healthcheck.onlinerestaurant.sator-it.dev:80)
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)**:

```
public static IServiceCollection AddHealthCheckExtension(this IServiceCollection services, IConfiguration configuration, IDatabaseStorageService databaseStorageService)
            {
                var healthCheckModelist = databaseStorageService.GetAllAsync<HealthCheckModel>().Result;
                var registerUrls = services.AddHealthChecks();
                var applicationUrl = configuration.GetSection("ApplicationUrl").GetSection("UrlToPing").Value;
                var baseUrl = configuration.GetSection("ApplicationUrl").GetSection("BaseUrl").Value;
                if (healthCheckModelist != null)
                {
                    string urlPath = string.Empty;
                    foreach (var item in healthCheckModelist)
                    {
                        urlPath = baseUrl;
                        urlPath += applicationUrl.Replace("[app]", item.ApplicationName);

                              registerUrls.AddUrlGroup(new Uri(urlPath),httpMethod:System.Net.Http.HttpMethod.Get, name:item.ApplicationName);
                        urlPath = string.Empty;
               
                    }
                }
                      services.AddHealthChecksUI(opt =>
            {
                opt.SetEvaluationTimeInSeconds(5); //time in seconds between check    
                opt.MaximumHistoryEntriesPerEndpoint(60); //maximum history of checks    
                opt.SetApiMaxActiveRequests(1); //api requests concurrency    
                opt.AddHealthCheckEndpoint("Online Resturant", "https://api.onlinerestaurant.sator-it.dev/health"); //map health check api    
            }).AddSqlServerStorage(configuration.GetConnectionString("DefaultConnection"));
           
                return services;
            }     endpoints.MapHealthChecks("/health", new HealthCheckOptions()
                    {
                        Predicate = _ => true,
                        ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse


                    });
                    endpoints.MapHealthChecksUI(setup =>
                    {
                        setup.UIPath = "/health-ui";
                        setup.ApiPath = "/health-json";
                    }).RequireAuthorization(new AuthorizeAttribute() { Roles = "Admin", });
                    ;:
```
****:

**LIve**:

- .NET Core 6 Blazor SErver
- Healthchecks latest
- Operative system: windows
- Others:

**Comment by sungam3r** [comment]
Closed due to inactivity. @ahmedshahjr please try with the latest v7 versions of packages and feel free to reopen if issue is still actual for you.
