### ISSUE TITLE
GetHealthReport threw an exception and/or  Microsoft.com article is out of date with current implementation

### ISSUE THREAD

**Issue by tellybrown** [Xabaril/AspNetCore.Diagnostics.HealthChecks#121]
This articles code sample doesn't match with the current code base.  Entries vs Results

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2#customize-output

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/057f4365f66d5753bd21c54d7cf99c4794c52246/src/HealthChecks.UI.Client/UIHealthReport.cs

```
    private static Task WriteResponse(HttpContext httpContext, 
        HealthReport result)
    {
        httpContext.Response.ContentType = "application/json";
        var json = new JObject(
            new JProperty("status", result.Status.ToString()),
            new JProperty("results", new JObject(result.Entries.Select(pair =>
                new JProperty(pair.Key, new JObject(
                    new JProperty("status", pair.Value.Status.ToString()),
                    new JProperty("description", pair.Value.Description),
                    new JProperty("data", new JObject(pair.Value.Data.Select(
                        p => new JProperty(p.Key, p.Value))))))))));
        return httpContext.Response.WriteAsync(
            json.ToString(Formatting.Indented));
    }
```

Causes this error:

HealthChecks.UI.Core.HostedService.HealthCheckReportCollector:Error: GetHealthReport threw an exception.

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: H. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at System.Net.Http.HttpResponseMessageExtensions.As[TContent](HttpResponseMessage response)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)

**Comment by unaizorrilla** [comment]
Hi @tellybrown

In the first link, the documentation show how create a response Writer for HealthChecks but this is not the Writer to be used for HealthChecksUI.
We have a package for this response writer, AspNetCore.HealthChecks.UI 

Please reas our docs and guides on rearme.md PR check samples on this repository.

**Comment by tellybrown** [comment]
Ok thanks.  I didnt realize that was your specific implementation.
