### ISSUE TITLE
OutOfMemoryException when on app service

### ISSUE THREAD

**Issue by youngcm2** [Xabaril/AspNetCore.Diagnostics.HealthChecks#122]
After deploying the appservice starts throwing this error. I have to restart the app to get it back up.

Formatting stinks so I attached screen shots.

**Startup.cs**

**HealthChecks**

`
services.AddHealthChecks()
                .AddSqlServer(_configuration["sql:connectionString"])
                .AddMongoDb(mongodbConnectionString: _configuration["mongo:connectionString"],
                    mongoDatabaseName: _configuration["mongo:databaseName"])
                .AddRedis(_configuration["redis:connectionString"])
                .AddAzureBlobStorage(_configuration["blobStorageOptions:uri"])
                .AddHangfire(options =>
                {
                    options.MinimumAvailableServers = 1;
                })
              .AddApplicationInsightsPublisher(_configuration["ApplicationInsights:InstrumentationKey"]);
`

**Middleware**

`
builder.UseHealthChecks("/health-check", new HealthCheckOptions
            {
                Predicate = _=>true,
                ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
            });
`

**StackTrace**

`
Health check "HealthChecks.Publisher.ApplicationInsights.ApplicationInsightsPublisher" threw an unhandled exception after 20.4038ms
System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal()
   at System.Threading.Thread.Start()
   at System.Threading.Thread.Start(Object parameter)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
   at System.Threading.Tasks.TaskScheduler.InternalQueueTask(Task task)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at System.Threading.Tasks.Task.InternalStartNew(Task creatingTask, Delegate action, Object state, CancellationToken cancellationToken, TaskScheduler scheduler, TaskCreationOptions options, InternalTaskOptions internalOptions)
   at Microsoft.ApplicationInsights.Channel.InMemoryTransmitter..ctor(TelemetryBuffer buffer)
   at Microsoft.ApplicationInsights.Channel.InMemoryChannel..ctor()
   at Microsoft.ApplicationInsights.Extensibility.TelemetrySink..ctor(TelemetryConfiguration telemetryConfiguration, ITelemetryChannel telemetryChannel)
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration..ctor(String instrumentationKey, ITelemetryChannel channel)
   at HealthChecks.Publisher.ApplicationInsights.ApplicationInsightsPublisher.PublishAsync(HealthReport report, CancellationToken cancellationToken)
   at Microsoft.Extensions.Diagnostics.HealthChecks.HealthCheckPublisherHostedService.RunPublisherAsync(IHealthCheckPublisher publisher, HealthReport report, CancellationToken cancellationToken)
`

![image](https://user-images.githubusercontent.com/862338/53807743-f479d900-3f15-11e9-8784-2bb1a91e4c14.png)

![image](https://user-images.githubusercontent.com/862338/53807718-e75cea00-3f15-11e9-9490-87bcf6081fe8.png)

![image](https://user-images.githubusercontent.com/862338/53807782-17a48880-3f16-11e9-9734-72f9a3d0724a.png)

**Comment by unaizorrilla** [comment]
¿version of ApplicationInsightsPublisher? Let me check ASAP

**Comment by lfraile** [comment]
I'm currently looking at it, Seems like some code not cleaned is creating multiple TelemetryConfiguration objects and never disposing them. 

Let me finish some tests.

**Comment by unaizorrilla** [comment]
Hi @youngcm2 

Closed with PR 123 from @lfraile.

We have a  mistake on latest @lfraile feature on this package. I think is solved, when appveyor finish the build a new package 2.2.3 will be on Nuget.

**Comment by unaizorrilla** [comment]
Hi @youngcm2 
Can close this issue if new package solve the problem?

**Comment by unaizorrilla** [comment]
I close the issue because no update from @youngcm2, if is already present please reopen it

**Comment by youngcm2** [comment]
I just let it run for 24h. It has fixed the issue.
