### ISSUE TITLE
Updating from 6.0.4 to 6.0.5 nuget UI packages causes JSON Parsing errors during startup

### ISSUE THREAD

**Issue by OneCrazyRussian** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1422]
**What happened**:
After I updated HealthChecks packages (UI, UI.Client, UI.InMemory.Storage) from 6.0.4 to 6.0.5 during app startup I receive following exception:
```
System.Text.Json.JsonException: The JSON value could not be converted to HealthChecks.UI.Core.UIHealthStatus. Path: $.Status | LineNumber: 0 | BytePositionInLine: 11.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAsObject(ReadStack& state, Utf8JsonReader& reader, Object& value)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.ReadConstructorArgumentsWithContinuation(ReadStack& state, Utf8JsonReader& reader, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReportAsync(HealthCheckConfiguration configuration) in /_/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 129
```

**Source code sample**:
I'm adding a sql server and minimal config in startup
```
builder.Services.AddHealthChecks().AddSqlServer(builder.Configuration.GetConnectionString("1"),name: "DB 1");

builder.Services.AddHealthChecksUI(options =>
{
    options.SetEvaluationTimeInSeconds(300); //Sets the time interval in which HealthCheck will be triggered
    options.MaximumHistoryEntriesPerEndpoint(50); //Sets the maximum number of records displayed in history
    options.AddHealthCheckEndpoint("Health Checks API", "/health"); //Sets the Health Check endpoint
}).AddInMemoryStorage(); //Here is the memory bank configuration
```

The health controller is as follows
```
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using System.Net;

namespace CustomerSupport.Web.NetCore.Controllers
{
    /// <summary>
    /// Controller to expose health check service
    /// </summary>
    public class HealthController : BaseController
    {
        private readonly HealthCheckService _healthCheckService;
        /// <summary>
        /// Dependency injection
        /// </summary>
        public HealthController(HealthCheckService healthCheckService)
        {
            _healthCheckService = healthCheckService;
        }

        /// <summary>
        ///     Get Health
        /// </summary>
        /// <remarks>Provides an indication about the health of the API</remarks>
        /// <returns>Health information</returns>
        /// <response code="200">API is healthy</response>
        /// <response code="503">API is not healthy</response>
        [HttpGet]
        public async Task<IActionResult> Get()
        {
            var report = await _healthCheckService.CheckHealthAsync();
            return report.Status == HealthStatus.Healthy ? 
                Ok(report) : StatusCode((int)HttpStatusCode.ServiceUnavailable, report); 
        }
    }
}
```
EDIT: forgot to add BaseController for clarity
```
    /// <summary>
    /// Base controller to set up default rounting options and attribures
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public class BaseController : ControllerBase
    {
    }
```

**Environment**:
Net 6, SDK 6.0.400
Windows 10 21H2
Microsoft.NetCore.App framework version 6.0.8

**Comment by classicSchmosby** [comment]
@OneCrazyRussian  i've just run into this too, glad I saw this post to avoid much time wasted - reverting back to 6.0.4 for now

**Comment by Smacl3r** [comment]
Hi, came across to the same issue
it looks like **Status** as an int value is not supported anymore.
Receiving errors if the status is Healthy but returned as int, example:
 ` {"Entries":{"Storage":{"Description":"Storage is reachable","Duration":"00:00:00.0000550","Status":2}},"Status":"Healthy","TotalDuration":"00:00:00.0002169"}`
Could this be re-added? It really messes up backwards compatibility. 
My guess that this is the related change: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/commit/42059b6121fc176face25df099c367c6081bf577#diff-a9b050ff0b49ac29a6867cc9ad7556bd7bc3e9454d172c617bc502bfd3c6bcb4R99

**Comment by sungam3r** [comment]
@Smacl3r You are right. This is because `allowIntegerValues = false`. I've reread discussion from #975. I tend to change this setting to `true`.
