### ISSUE TITLE
Unspecified addresses that cannot be used as a target address

### ISSUE THREAD

**Issue by Hu-bert** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1462]
**What happened**:
I get error
![Zrzut ekranu 2022-09-27 003515](https://user-images.githubusercontent.com/24474894/192392671-cb71f3cf-0055-477d-8eda-831923050747.png)
> IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'hostName') ([::]:80)
```
Sep 27 12:32:00 AM  info: System.Net.Http.HttpClient.health-checks.LogicalHandler[100]
Sep 27 12:32:00 AM        Start processing HTTP request GET http://[::]/hc
Sep 27 12:32:00 AM  info: System.Net.Http.HttpClient.health-checks.ClientHandler[100]
Sep 27 12:32:00 AM        Sending HTTP request GET http://[::]/hc
Sep 27 12:32:00 AM  fail: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
Sep 27 12:32:00 AM        GetHealthReport threw an exception when trying to get report from /hc configured with name Checks.
Sep 27 12:32:00 AM        System.Net.Http.HttpRequestException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'hostName') ([::]:80)
Sep 27 12:32:00 AM         ---> System.ArgumentException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'hostName')
Sep 27 12:32:00 AM           at System.Net.Dns.GetHostEntryOrAddressesCoreAsync(String hostName, Boolean justReturnParsedIp, Boolean throwOnIIPAny, Boolean justAddresses, AddressFamily family, CancellationToken cancellationToken)
Sep 27 12:32:00 AM           at System.Net.Dns.GetHostAddressesAsync(String hostNameOrAddress, AddressFamily family, CancellationToken cancellationToken)
Sep 27 12:32:00 AM           at System.Net.Sockets.SocketAsyncEventArgs.DnsConnectAsync(DnsEndPoint endPoint, SocketType socketType, ProtocolType protocolType)
Sep 27 12:32:00 AM           at System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e, Boolean userSocket, Boolean saeaCancelable)
Sep 27 12:32:00 AM           at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
Sep 27 12:32:00 AM           at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
Sep 27 12:32:00 AM           at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
Sep 27 12:32:00 AM           --- End of inner exception stack trace ---
Sep 27 12:32:00 AM           at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
Sep 27 12:32:00 AM           at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Sep 27 12:32:00 AM           at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Sep 27 12:32:00 AM           at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
Sep 27 12:32:00 AM           at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
Sep 27 12:32:00 AM           at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Sep 27 12:32:00 AM           at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
Sep 27 12:32:00 AM           at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Sep 27 12:32:00 AM           at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Sep 27 12:32:00 AM           at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Sep 27 12:32:00 AM           at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Sep 27 12:32:00 AM           at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReportAsync(HealthCheckConfiguration configuration) in /_/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 141
```

**What you expected to happen**:
I was expecting it to work like it does on localhost
![Zrzut ekranu 2022-09-27 003742](https://user-images.githubusercontent.com/24474894/192392950-a26526e9-874f-4878-be75-4988a53aec91.png)

**How to reproduce it (as minimally and precisely as possible)**:
The problem is with the docker container with Linux, port 80 and 443.

**Source code sample**:
appsettings.json:
```json
"HealthChecksUI": {
    "HealthChecks": [
      {
        "Name": "Checks",
        "Uri": "/hc"
      }
    ],
    "EvaluationTimeInSeconds": 30
  }, 
```
Program.cs:
```csharp 

builder.Services.ConfigureHealthCheck(connectionString);

. . .

    public static void ConfigureHealthCheck(this IServiceCollection services, string? connectionString)
    {
      services.AddHealthChecks()
        .AddNpgSql(connectionString, tags: new[] { "db", "supabase", "postgre" }, name: "Database availability");

      services.AddHealthChecks()
        .AddNpgSql(connectionString, "SELECT 1;", tags: new[] { "db", "postgre" }, name: "Database query");

      services.AddHealthChecksUI()
        .AddInMemoryStorage();
    }

. . .

app.MapHealthChecks("/hc", new HealthCheckOptions
{
  Predicate = _ => true,
  ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
});

app.MapHealthChecksUI(setup =>
{
  setup.UIPath = "/hc-ui";
  setup.ApiPath = "/hc-ui-api";
  setup.PageTitle = "Health Checks UI";
});
```

**Anything else we need to know?**:
Docker deployed on render.com

**Environment**:
- .NET version : 6 (Minimal API)
- Healthchecks version: 6.0.0.0
- Operative system: Linux

**Comment by Hu-bert** [comment]
I found @MaxThom [comment](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/702#issuecomment-784643959) and it solved my problem.

**Comment by taiielmehdi** [comment]
@Hu-bert i have the same error but when i put the url in browser i get this error ' this page can’t be found'

**Comment by Hu-bert** [comment]
@taiielmehdi can you show your code with configuration?

**Comment by douglasg14b** [comment]
Same error as well when using relative URLs
