### ISSUE TITLE
NET6  Healthchecks.ui error

### ISSUE THREAD

**Issue by JavaScript-zt** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1464]
Host terminated unexpectedly!Method not found: 'Void Microsoft.EntityFrameworkCore.MutablePropertyExtensions.SetValueComparer(Microsoft.EntityFrameworkCore.Metadata.IMutableProperty, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer)'.Host terminated unexpectedly!Method not found: 'Void Microsoft.EntityFrameworkCore.MutablePropertyExtensions.SetValueComparer(Microsoft.EntityFrameworkCore.Metadata.IMutableProperty, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer)'.

System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.MutablePropertyExtensions.SetValueComparer(Microsoft.EntityFrameworkCore.Metadata.IMutableProperty, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer)'.
System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.MutablePropertyExtensions.SetValueComparer(Microsoft.EntityFrameworkCore.Metadata.IMutableProperty, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer)'.
   at HealthChecks.UI.Core.Data.Configuration.HealthCheckExecutionEntryMap.Configure(EntityTypeBuilder`1 builder)
   at HealthChecks.UI.Core.Data.Configuration.HealthCheckExecutionEntryMap.Configure(EntityTypeBuilder`1 builder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration`1 configuration)
   at HealthChecks.UI.Core.Data.HealthChecksDb.OnModelCreating(ModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration`1 configuration)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at HealthChecks.UI.Core.Data.HealthChecksDb.OnModelCreating(ModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()

**Comment by JavaScript-zt** [comment]
help

**Comment by Hu-bert** [comment]
Did you used AddInMemoryStorage(); with service?
Add code with your config
