### ISSUE TITLE
Exception because of earlier set Cache-Control header

### ISSUE THREAD

**Issue by espenrl** [Xabaril/AspNetCore.Diagnostics.HealthChecks#15]
```
System.ArgumentException: An item with the same key has already been added.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowDuplicateKeyException()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Add(String key, StringValues value)
   at HealthChecks.UI.Core.UIResourcesMapper.<>c__DisplayClass2_0.<Map>b__3(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
```

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/94bf1f08ee7b539f91536c60d09c6e5258e443e3/src/HealthChecks.UI/Core/UIResourceMapper.cs#L39

In my host the Cache-Control header is already set before processing the HealtChecks UI middleware.

**Comment by unaizorrilla** [comment]
Could you put UseHealthChecksUI on app.Map that create a pipeline for the UI

**Comment by espenrl** [comment]
That will not work in my case as the `Cache-Control` is set by a previously run middleware. I have 17 different middlewares in my pipeline and the ordering of them has importance regarding security. The health check UI is only available to admins as it  disclose a lot of information about the app (around 50-60 health checks).

**Comment by unaizorrilla** [comment]
Ok i try to fix it checking if it is already set.

**Comment by unaizorrilla** [comment]
Can yoy try 2.2.2 version of UI and check if issue is solved?

**Comment by espenrl** [comment]
Yes it works. Thanks!

**Comment by unaizorrilla** [comment]
Ok, close this issue, thanks for fill this issue @espenrl
