### ISSUE TITLE
AzureServiceBus health check requires listen scope breaks security concerns

### ISSUE THREAD

**Issue by marioleed** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1556]
Please, fill the following sections to help us fix the issue

**What happened**:
Upgraded to AspNetCore.HealthChecks.AzureServiceBus v6.1.0 which included this breaking change #1503.

We have multiple "external" Queues with Sender claim only (valid security reasons) and since PeekMessageAsync requires Listen claim the following error happens:

```
[11:17:18 WRN] Health check [redacted] ServiceBus - '[redacted]' queue with status Degraded completed after 11589.785ms with message 'null'
System.UnauthorizedAccessException: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://[redacted].servicebus.windows.net/[redacted]/$management'. TrackingId:[redacted], SystemTracker:NoSystemTracker, Timestamp:2022-12-05T10:17:18
For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.PeekMessagesInternalAsync(Int64 sequenceNumber, Int32 messageCount, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<PeekMessagesAsync>b__58_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.PeekMessagesAsync(Nullable`1 sequenceNumber, Int32 messageCount, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.PeekMessagesInternalAsync(Nullable`1 sequenceNumber, Int32 maxMessages, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.PeekMessageAsync(Nullable`1 fromSequenceNumber, CancellationToken cancellationToken)
   at HealthChecks.AzureServiceBus.AzureServiceBusQueueHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken) in /_/src/HealthChecks.AzureServiceBus/AzureServiceBusQueueHealthCheck.cs:line 28
```

**What you expected to happen**:
Health check should work with Listen or Sender claim.

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade to AspNetCore.HealthChecks.AzureServiceBus v6.1.0 and do a health check on a Service Bus Queue with only Sender claim.

**Source code sample**:

**Anything else we need to know?**:
We use user assigned managed identity with role assignments, e.g. Azure Service Bus Data Sender
Using only Sender claim is a valid security reason (else it would be unnecessary to have claims for both Listen and Sender).

Also, this change was a breaking change that became hidden as it was released with a different, non-breaking, change #1540. I think this could have been avoided if the PR #1504 would have bumped the version number. This is not to blame, but to not forget to bump versions for future changes.

**Environment**:

- .NET Core version - N/A
- Healthchecks version AspNetCore.HealthChecks.AzureServiceBus v6.1.0
- Operative system: - N/A
- Others:

**Comment by marioleed** [comment]
I guess I can look into it sometime this week.

**Comment by marioleed** [comment]
@sungam3r A PR proposal is up, if you would like to have a look 🙂
