### ISSUE TITLE
Azure Service Bus subscription health check failure when auto-forwarding is enabled

### ISSUE THREAD

**Issue by CoeckelberghPJ** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1560]
After upgrading from version 6.0.4 to version 6.1.0 we get a failing Azure Service Bus Subscription health check because auto-forwarding is enabled on that subscription. 
Since 6.1.0 a PeekMessageAsync is used in the CheckHealthAsync method of AzureServiceBusSubscriptionHealthCheck which causes this exception to be thrown. Reverting to 6.0.4 returns a healthy status.

`System.InvalidOperationException: Cannot create a message browser on an entity with auto-forwarding enabled. Reference:9c5fe96d-d497-407c-b0b3-70ea442c9ba7, TrackingId:f060685a-93c1-4823-9ac7-50a2c15197ed_B30, SystemTracker:asbweucapdpj3:Topic:bundle-1|subscriptionname, Timestamp:2022-12-13T07:48:07 Reference:4d9455d8-0bd3-4b35-ab33-fb6120f858c7, TrackingId:c96cc1ba-29ed-4eaf-8ed6-8ab4e7297ec8_G11, SystemTracker:NoSystemTracker, Timestamp:2022-12-13T07:48:07
For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.PeekMessagesInternalAsync(Int64 sequenceNumber, Int32 messageCount, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<PeekMessagesAsync>b__58_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.PeekMessagesAsync(Nullable`1 sequenceNumber, Int32 messageCount, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.PeekMessagesInternalAsync(Nullable`1 sequenceNumber, Int32 maxMessages, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.PeekMessageAsync(Nullable`1 fromSequenceNumber, CancellationToken cancellationToken)
   at HealthChecks.AzureServiceBus.AzureServiceBusSubscriptionHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken) in /_/src/HealthChecks.AzureServiceBus/AzureServiceBusSubscriptionHealthCheck.cs:line 30`

Please, fill the following sections to help us fix the issue

**What happened**: Upgraded AspNetCore.HealthChecks.AzureServiceBus from 6.0.4 to 6.1.0

**What you expected to happen**: Health checks to continue working

**How to reproduce it (as minimally and precisely as possible)**:
- Setup a subscription using auto-forwarding.
- Add a health check to that subscription

**Environment**:

- .NET Core version: .net core 6
- Healthchecks version: 6.1.0

**Comment by sungam3r** [comment]
May be related to #1556

**Comment by marioleed** [comment]
If #1565 is merged and released you will have the option to use the "old" mode without PeekMessageAsync.

**Comment by sungam3r** [comment]
Closed due to inactivity.
