### ISSUE TITLE
404 response code thrown JsonException 

### ISSUE THREAD

**Issue by masterged** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1620]
**What happened**:
 When endpoint return 404 code JsonException was thrown.

System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStreamAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReportAsync(HealthCheckConfiguration configuration) in /_/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 129

**What you expected to happen**:
Check response code before serialization.

**How to reproduce it (as minimally and precisely as possible)**:
Call url with bad endpoint.

- .NET Core version 7
- Healthchecks version 6.0.5

**Comment by sungam3r** [comment]
> Check response code before serialization.

OK. But the question is what do you expect after that?

**Comment by sungam3r** [comment]
Return `UIHealthReport` built from occured exception? Or return `UIHealthReport` with custom error message?

**Comment by masterged** [comment]
I think it may be a custom error message. Smthn like this
`                using (response)
                {
                    if(!response.IsSuccessStatusCode) throw new InvalidOperationException("Http response is not in valid state");
                    var report = await response.Content.ReadFromJsonAsync<UIHealthReport>(_options).ConfigureAwait(false);
                    if (report == null)
                        throw new InvalidOperationException($"{nameof(HttpContentJsonExtensions.ReadFromJsonAsync)} returned null");
                    return report;
                }`

**Comment by sungam3r** [comment]
PR is welcome.

**Comment by sungam3r** [comment]
Will be published in v7.

**Comment by keremcadirci** [comment]
After this changes we are unable to see anymore Endpoint details of an Unhealty(503) state:
Before :
![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/16028850/b523c0d4-22b6-43db-847f-69daf39ca999)

After:
![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/16028850/cec533bd-4af7-4a8e-b500-7a0f44e641ba)

**Comment by sungam3r** [comment]
See #1986

**Comment by sungam3r** [comment]
https://www.nuget.org/packages/AspNetCore.HealthChecks.UI/7.0.2
