### ISSUE TITLE
After upgrading to Net6, AddHealthChecksUI throws exceptions 

### ISSUE THREAD

**Issue by eltonina** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1650]
**What happened**:

When Executing database migrations, this error is thrown 

> Method not found: 
> 
> 'Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.OperationBuilder`1<Microsoft.EntityFrameworkCore.Migrations.Operations.CreateIndexOperation> Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder.CreateIndex(System.String, System.String, System.String, System.String, Boolean, System.String)'.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Source code sample**:

```
            builder.Services
                .AddHealthChecksUI(setup =>
                {
                    setup.SetEvaluationTimeInSeconds((int)TimeSpan.FromMinutes(5).TotalSeconds);
                    setup.AddHealthCheckEndpoint("app", configuration["HealthChecksUI:HealthCheckEndpoint"] ?? "/status");
                })
                .AddPostgreSqlStorage(connectionString);
```

**Anything else we need to know?**:
Disabling the migration,  throw another ugly error:
` setup.DisableDatabaseMigrations(),  `

> 
> 42P01: relation "Configurations" does not exist
> 
> POSITION: 41

**Stack trace **
```
   at Npgsql.Internal.NpgsqlConnector.<<ReadMessage>g__ReadMessageLong|225_0>d.MoveNext()
   at Npgsql.NpgsqlDataReader.<NextResult>d__47.MoveNext()
   at Npgsql.NpgsqlDataReader.<NextResult>d__47.MoveNext()
   at Npgsql.NpgsqlCommand.<ExecuteReader>d__124.MoveNext()
   at Npgsql.NpgsqlCommand.<ExecuteReader>d__124.MoveNext()
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReaderAsync>d__117.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__19.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__19.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<InitializeReaderAsync>d__21.MoveNext()
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__20.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.<SingleAsync>d__14`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.<SingleAsync>d__14`1.MoveNext()
   at HealthChecks.UI.Core.HostedService.UIInitializationHostedService.<InitializeDatabaseAsync>d__6.MoveNext()
   at HealthChecks.UI.Core.HostedService.UIInitializationHostedService.<StartAsync>d__4.MoveNext()
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.<ExecuteAsync>d__5.MoveNext()
   at Microsoft.AspNetCore.Hosting.WebHost.<StartAsync>d__27.MoveNext()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
```

- .NET Core version **NET6**
- Healthchecks version **6.0.4**

**Comment by JusteZilinskaite** [comment]
Experiencing the same issue;

**Comment by sungam3r** [comment]
Different versions of EF packages may be used on .NET Core 6 platform. Personally I do not use any UI package from this repo but I help to maintain them and keep them up to date as much as I can. You may try latest preview v7 packages. See https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/1593

**Comment by sungam3r** [comment]
Closed due to inactivity.
