### ISSUE TITLE
Error when upgrading to .NET 7 and using 7.0.0-rc2.7

### ISSUE THREAD

**Issue by moraleslos** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1651]
Upgrading my app to .NET 7 as well as upgrading AspNetCore.HealthChecks.UI to 7.0.0-rc2.7 and AspNetCore.HealthChecks.SqlServer to 7.0.0-rc2.10 (among other AspNetCore.HealthChecks packages) causes errors.  I get the following for SQLServer:

> [Error] (Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware) An unhandled exception has occurred while executing the request.
System.ArgumentNullException: Value cannot be null. (Parameter 'options.CommandText')
   at Guard.ThrowIfNull[T](T argument, Boolean throwOnEmptyString, String paramName) in /_/src/CallerArgumentExpressionAttribute.cs:line 50
   at HealthChecks.SqlServer.SqlServerHealthCheck..ctor(SqlServerHealthCheckOptions options) in /_/src/HealthChecks.SqlServer/SqlServerHealthCheck.cs:line 16
   at Microsoft.Extensions.DependencyInjection.SqlServerHealthCheckBuilderExtensions.<>c__DisplayClass3_0.<AddSqlServer>b__0(IServiceProvider sp) in /_/src/HealthChecks.SqlServer/DependencyInjection/SqlServerHealthCheckBuilderExtensions.cs:line 80
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.RunCheckAsync(HealthCheckRegistration registration, CancellationToken cancellationToken)
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.RunCheckAsync(HealthCheckRegistration registration, CancellationToken cancellationToken)
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.CheckHealthAsync(Func`2 predicate, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

For the UICore I get the following error:

> [Error] (HealthChecks.UI.Core.HostedService.HealthCheckReportCollector) GetHealthReport threw an exception when trying to get report from https://localhost:8080/health configured with name FireApp.
System.Text.Json.JsonException: 'S' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'S' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStreamAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReportAsync(HealthCheckConfiguration configuration) in /_/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 126

**Comment by sungam3r** [comment]
How do you register SqlServer HC? I think you call `AddSqlServer` method specifying `null` for command text.

**Comment by moraleslos** [comment]
didn't notice the change there.  yes you're correct.  added that in and it works now.  thank you.

**Comment by sungam3r** [comment]
Most probably you have to enable nullable annotations for your project (`<Nullable>enable</Nullable>`) to make such issues obvious. For the second error from initial post I think it's gone after you fix `null` in command text.
