### ISSUE TITLE
Does healthcheck close the connection properly?

### ISSUE THREAD

**Issue by khteh** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1808]
Please, fill the following sections to help us fix the issue

**What happened**:
I hit this error from pgadmin4 web connecting to an AWS RDS cluster of 2 nodes. There are on average 5 connections to the write instance. 

https://docs.sqlalchemy.org/en/20/errors.html#error-3o7r

`program.cs`:
```
    builder.Services.AddHealthChecks()
        .AddLivenessHealthCheck("Liveness", HealthStatus.Unhealthy, new List<string>() { "live" })
        .AddReadinessHealthCheck("Readiness", HealthStatus.Unhealthy, new List<string> { "ready" })
        .AddNpgSql(builder.Configuration["ConnectionStrings:Default"], "SELECT 1;", null, "PostgreSQL Health Check", HealthStatus.Unhealthy, new List<string> { "Database" })
        .AddDbContextCheck<MyDbContext>("MyDbContext", HealthStatus.Unhealthy, new List<string> { "DbContext" })
        .AddDbContextCheck<MyIAMDbContext>("MyIAMDbContext", HealthStatus.Unhealthy, new List<string> { "DbContext" });
    app.MapHealthChecks("/health/live", new HealthCheckOptions()
    {
        AllowCachingResponses = false,
        Predicate = healthCheck => healthCheck.Tags.Contains("live") || healthCheck.Tags.Contains("Database") || healthCheck.Tags.Contains("DbContext")
    });
    app.MapHealthChecks("/health/ready", new HealthCheckOptions()
    {
        AllowCachingResponses = false,
        Predicate = healthCheck => healthCheck.Tags.Contains("ready") || healthCheck.Tags.Contains("Database") || healthCheck.Tags.Contains("DbContext")
    });
```
k8s healthcheck frequency is 5 seconds.

**What you expected to happen**:
Healthcheck service to properly close connections.

**How to reproduce it (as minimally and precisely as possible)**:

**Source code sample**:

**Anything else we need to know?**:
```
[pgadmin-0] 2023-04-28 09:03:33,207: ERROR	pgadmin:	QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
[pgadmin-0] Traceback (most recent call last):
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask/app.py", line 1821, in full_dispatch_request
[pgadmin-0]     rv = self.preprocess_request()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask/app.py", line 2312, in preprocess_request
[pgadmin-0]     rv = self.ensure_sync(before_func)()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask_principal.py", line 477, in _on_before_request
[pgadmin-0]     identity = loader()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask_security/core.py", line 708, in _identity_loader
[pgadmin-0]     if not isinstance(current_user._get_current_object(), AnonymousUserMixin):
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/werkzeug/local.py", line 520, in _get_current_object
[pgadmin-0]     return get_name(local())  # type: ignore
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask_login/utils.py", line 25, in <lambda>
[pgadmin-0]     current_user = LocalProxy(lambda: _get_user())
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask_login/utils.py", line 372, in _get_user
[pgadmin-0]     current_app.login_manager._load_user()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask_login/login_manager.py", line 364, in _load_user
[pgadmin-0]     user = self._user_callback(user_id)
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask_security/core.py", line 638, in _user_loader
[pgadmin-0]     user = _security.datastore.find_user(fs_uniquifier=str(user_id))
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask_security/datastore.py", line 782, in find_user
[pgadmin-0]     return query.filter_by(**kwargs).first()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2752, in first
[pgadmin-0]     return self.limit(1)._iter().first()  # type: ignore
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2855, in _iter
[pgadmin-0]     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
[pgadmin-0]     return self._execute_internal(
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2114, in _execute_internal
[pgadmin-0]     conn = self._connection_for_bind(bind)
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1981, in _connection_for_bind
[pgadmin-0]     return trans._connection_for_bind(engine, execution_options)
[pgadmin-0]   File "<string>", line 2, in _connection_for_bind
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
[pgadmin-0]     ret_value = fn(self, *arg, **kw)
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1108, in _connection_for_bind
[pgadmin-0]     conn = bind.connect()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3251, in connect
[pgadmin-0]     return self._connection_cls(self)
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
[pgadmin-0]     self._dbapi_connection = engine.raw_connection()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
[pgadmin-0]     return self.pool.connect()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 455, in connect
[pgadmin-0]     return _ConnectionFairy._checkout(self)
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
[pgadmin-0]     fairy = _ConnectionRecord.checkout(pool)
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
[pgadmin-0]     rec = pool._do_get()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 157, in _do_get
[pgadmin-0]     raise exc.TimeoutError(
[pgadmin-0] sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
[pgadmin-0] 118.201.248.18 - - [28/Apr/2023:09:03:33 +0000] "GET / HTTP/1.1" 500 206 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.3
```

**Environment**:

- .NET Core version `7.0.105`
- Healthchecks version `6.0.2`
- Operative system: `Ubuntu 23.04`
- Others:

**Comment by sungam3r** [comment]
Answering the initial question - yes, connection is disposed, see https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/release-npgsql-6.0.2/src/HealthChecks.NpgSql/NpgSqlHealthCheck.cs#L23
