### ISSUE TITLE
NullReferenceException in HealthCheck.UI.Middleware

### ISSUE THREAD

**Issue by mmacagno** [Xabaril/AspNetCore.Diagnostics.HealthChecks#183]
I am sure I am doing something wrong... but not sure what...

I have a aspnetcore 2.2 website. My intention is (was) to host the healthcheck ui on the same website of the application.

When I go to the /healthchecks-ui page, I get an error:

![image](https://user-images.githubusercontent.com/2315384/57819267-8aaf5400-773c-11e9-94e7-e450d1d00c9f.png)

The exception on the 500 errors in the healthchecks API is:
`System.NullReferenceException: Object reference not set to an instance of an object.
   at HealthChecks.UI.Middleware.UIApiEndpointMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\IdentityServerMiddleware.cs:line 72
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\MtlsTokenEndpointMiddleware.cs:line 60
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

Not sure what's going on.
Repro both on local server and on Azure. (not using IIS but Kestrel)

Here below my (standard) configuration.
Thanks

---

Startup.cs (ConfigureServices):

`            services.AddHealthChecks()
                .AddApplicationInsightsPublisher()
                .AddSqlServer(
                    connectionString: Configuration.GetConnectionString("SensoriaDbContextConnection"),
                    healthQuery: "SELECT 1;",
                    name: "sql",
                    failureStatus: HealthStatus.Unhealthy,
                    tags: new string[] { "db", "sql", "sqlserver" })
                .AddIdentityServer(
                    idSvrUri: new Uri("https://auth.sensoria.io"), // Note the healthcheck is local to all servers, so local.sensoria.io will resolve for auth.sensoria.io as well
                    name: "self-identityserver",
                    failureStatus: HealthStatus.Unhealthy,
                    tags: new string[] { "oidc" });`

Startup.cs (Configure):

`            app.UseSwagger();
            app.UseSwaggerUI(option =>
            {
                option.SwaggerEndpoint("/swagger/v1/swagger.json", "Sensoria IDP Server API");
            });

            app.UseHealthChecks("/healthz", new HealthCheckOptions()
            {
                Predicate = _ => true,
                ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
            });

            app.UseHealthChecksUI();

            app.UseMvcWithDefaultRoute();`

appsettings:
`  "HealthChecks-UI": {
    "HealthChecks": [
      {
        "Name": "Health Dashboard",
        "Uri": "https://auth.sensoria.io/healthz"
      }
    ],
    "Webhooks": [],
    "EvaluationTimeOnSeconds": 10,
    "MinimumSecondsBetweenFailureNotifications": 60    
  },
`

**Comment by unaizorrilla** [comment]
Hi, we have a sample with the UI and healthchecks in the same project, can you checkout and confirm if work well for you!

**Comment by mmacagno** [comment]
I thought I checked already, but will double check and confirm

**Comment by mmacagno** [comment]
I was able to run the sample project. All other project with both UI and API are still failing, but I guess there is something at play with authentication.

**Comment by yogesh451** [comment]
It is the cause of  'services.AddHealthChecksUI();' missed in ConfigureServices in my case.

After added above one working fine.
