### ISSUE TITLE
"e.map is not a function" JS exception in the UI

### ISSUE THREAD

**Issue by zorgoz** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1839]
Similar issue: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/661

UI version: 7.0.0-rc2.7

I am encountering following exception, resulting in the UI being totally empty:

```
90  TypeError: e.map is not a function
    at healthchecks-bundle.js:6:124398
    at t.LivenessTable (healthchecks-bundle.js:6:124567)
    at qi (vendors-dll.js:290:57929)
    at hs (vendors-dll.js:290:104168)
    at lu (vendors-dll.js:290:96716)
    at su (vendors-dll.js:290:96641)
    at Xs (vendors-dll.js:290:93671)
    at vendors-dll.js:290:45313
    at t.unstable_runWithPriority (vendors-dll.js:298:3844)
    at Ia (vendors-dll.js:290:45022)
es @ vendors-dll.js:290
healthchecks-bundle.js:1  Uncaught TypeError: e.map is not a function
    at healthchecks-bundle.js:6:124398
    at t.LivenessTable (healthchecks-bundle.js:6:124567)
    at qi (vendors-dll.js:290:57929)
    at hs (vendors-dll.js:290:104168)
    at lu (vendors-dll.js:290:96716)
    at su (vendors-dll.js:290:96641)
    at Xs (vendors-dll.js:290:93671)
    at vendors-dll.js:290:45313
    at t.unstable_runWithPriority (vendors-dll.js:298:3844)
    at Ia (vendors-dll.js:290:45022)
```
Setup is:

```
builder.Services.AddHealthChecks().AddDbContextCheck<NrgContext>();
builder.Services.AddHealthChecksUI().AddSqliteStorage("Data Source = healthchecks.db");
...
app.UseHealthChecks("/health", new HealthCheckOptions { ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse });
app.MapHealthChecksUI(o => { o.UseRelativeApiPath = true; o.ApiPath = "/health"; });
```

`/health` response: 
`{"status":"Healthy","totalDuration":"00:00:00.0695283","entries":{"NrgContext":{"data":{},"duration":"00:00:00.0270006","status":"Healthy","tags":[]}}}`
(it _is_ fetched by the UI, according to the network tab)

**Comment by sungam3r** [comment]
PR to fix this is welcome.

**Comment by cieciurm** [comment]
Hello,

I've spent some time looking into this issue and have some conclusions.

I've reproduced this issue `"e.map is not a function"`,
but I'm wondering if it's not due to a fact of **misuse of HealthCheck URL and HealthCheckUI back-end URL**.

`app.UseHealthChecks("/health", new HealthCheckOptions { ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse });`

This line configures the HealthCheck URL. So when you call /health you get a Health Check Result, also a ResponseWriter is specificed so it's formatted as nice JSON. All good.

`app.MapHealthChecksUI(o => { o.UseRelativeApiPath = true; o.ApiPath = "/health"; });`

This line configures HealthCheckUI back-end URL. This is the back-end URL front-end is polling to get summary of all Health Checks displayed by the UI. In this scenario, there is only one Health Check but there could be more. That's why the expected response is an array of HealthCheck results.

Please see the comparison of Health Check response vs Health Check UI back-end response

```json
{
  "status": "Healthy",
  "totalDuration": "00:00:00.0018501",
  "entries": { /* ... */ }
}
```

```json
[
    {
        "id": 1,
        "status": "Healthy",
        "onStateFrom": "2023-07-26T10:37:56.660717+02:00",
        /* ... */
     }
]
```

In the setup provided in the issue, identical URL is used as both Health Check URL and Health Check UI back-end URL which is incorrect.

Health Check UI back-end is iterating over all configured Health Checks and combines them in a single response (with multiple Health Check Results).

The issue can be mitigated by using any different Health Check UI back-end URL. For example:

`app.MapHealthChecksUI(o => { o.UseRelativeApiPath = true; o.ApiPath = "/health-all"; });`

Could you try this solution @zorgoz?

I don't think it's a bug in this package, but you can prove me wrong 😄 .

cc @sungam3r

**Comment by sungam3r** [comment]
Sorry, almost all UI stuff is out of my scope for now. So far I am not ready to discuss this area.

**Comment by cieciurm** [comment]
ping @zorgoz

**Comment by cieciurm** [comment]
ping @zorgoz
