### ISSUE TITLE
Type mismatch between UIHealthReportEntry and HealthCheckResult

### ISSUE THREAD

**Issue by rvanheest** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1944]
**What happened**:
When an exception occurs during a healthcheck, a `new HealthCheckResult` is created containing this exception. See for example https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Uris/UriHealthCheck.cs#L75 and https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.SqlServer/SqlServerHealthCheck.cs#L40.

In the `/health` endpoint this exception will be presented like the object that it is:

```json
{
  "Entries": {
    "MyWebApi": {
      "Data": {},
      "Description": null,
      "Duration": "00:00:02.0428757",
      "Exception": {
        "ClassName": "System.Threading.Tasks.TaskCanceledException",
        "Message": "The operation was canceled.",
        "Data": null,
        "InnerException": // some inner exception,
        "HelpURL": null,
        "StackTraceString": // some stacktrace,
        "RemoteStackTraceString": null,
        "RemoteStackIndex": 0,
        "ExceptionMethod": null,
        "HResult": -2146233029,
        "Source": "System.Net.Http",
        "WatsonBuckets": null
      },
      "Status": "Unhealthy",
      "Tags": []
    }
  },
  "Status": "Unhealthy",
  "TotalDuration": "00:00:02.0472594"
}
```

In turn the `/health` endpoint is polled by the health-ui's backend process and the resulting JSON is created into a `UIHealthReport` in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs#L134. This `UIHealthReport` contains a collection of `UIHealthReportEntry` elements, which is nearly identical to the `HealthCheckResult` mentioned above. The difference is that in `HealthCheckResult` the `Exception` field is of type `Exception`, whereas in `UIHealthReportEntry` it is of type `String`.

This causes the following exception in the health-ui process:

```
[21:05:44 ERR] GetHealthReport threw an exception when trying to get report from https://localhost:5101/health configured with name MyWebApi.
System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.Entries.MyWebApi.Exception | LineNumber: 6 | BytePositionInLine: 20.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a string.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedString(JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.Serialization.Converters.StringConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.TryRead[TArg](ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo, TArg& arg)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.ReadAndCacheConstructorArgument(ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.ReadConstructorArgumentsWithContinuation(ReadStack& state, Utf8JsonReader& reader, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo, ReadStack& state)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStreamAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReportAsync(HealthCheckConfiguration configuration) in /_/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 126
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Source code sample**:

**Anything else we need to know?**:

**Environment**:

- .NET Core version
- Healthchecks version
- Operative system:
- Others:

**Comment by cieciurm** [comment]
I wonder if it's due to #1869 - is Newtonsoft JSON so smart to deserialize from `Exception` to `string`...? Or there was a custom deserialization for this?

Solutions could be:
- to split the models exchanged between _Health Check Source and Health Check UI back-end_ vs. _Health Check UI back-end and Health Check UI front-end_
- implement some custom deserialization from Exception to string for this purpose

What are you ideas @sungamer ?

**Comment by rvanheest** [comment]
Probably not #1869, as this was only merged last week and to my knowledge there hasn't been a release since then.
Looking through the Git history of `UIHealthReportEntry`, it has always had a property `Exception` of type `string`, so this might as well be an old bug. I've only recently started using the health-ui, so I just noticed it while testing.

**Comment by cieciurm** [comment]
Hi again @rvanheest,

I've tried to reproduce this issue, and so far no luck - in both attempts exception was a `string` and not `Exception`.
I tried two approaches:

1. Returning `new HealthCheckResult(context.Registration.FailureStatus, exception: exception)`

Where `exception` was an exception, that I have manually created.

Response was:

```json
{
  "status": "Unhealthy",
  "totalDuration": "00:00:00.9023163",
  "entries": {
    "exceptionHealthCheck": {
      "data": {},
      "description": "message",
      "duration": "00:00:00.8445743",
      "exception": "message",
      "status": "Unhealthy",
      "tags": []
    }
  }
}
```

2. Using `.AddUrlGroup(new Uri("url-requiring-authentication"))`

Response was:
```json
{
  "status": "Unhealthy",
  "totalDuration": "00:00:01.4599970",
  "entries": {
    "uriCheck": {
      "data": {},
      "description": "Discover endpoint #0 is not responding with code in 200...299 range, the current 
status is Unauthorized.",
      "duration": "00:00:00.5876570",
      "status": "Unhealthy",
      "tags": []
     }
  }
}
```

Could you let me know, how are you getting the Exception returned?

Thanks!

**Comment by rvanheest** [comment]
Hi @cieciurm, thanks for taking the time to try to reproduce this bug. My setup is as follows (probably quite standard, but just for completeness):

```cs
services.AddHealthChecks().AddUrlGroup(
  sp => "<my url>",
  name: "MyDependencyWebApi",
  timeout: TimeSpan.FromSecondes(2),
  failureStatus: HealthStatus.Unhealthy
)

services.AddHealthChecksUI(settings =>
{
    settings.AddHealthCheckEndpoint("MyWebApi", "the URI to the /health endpoint listed below");
}).AddInMemoryStorage();

app.UseEndpoints(endpoints =>
{
    // map my regular webapi+swagger

    // create the endpoint for the health json
    endpoints.MapHealthChecks("/health", new HealthCheckOptions
    {
        ResponseWriter = WriteHealthCheckFormattedResponse,
        Predicate = _ => true,
    });

    endpoints.MapHealthChecksUI();
});

private static async Task WriteHealthCheckFormattedResponse(HttpContext context, HealthReport report)
{
    var result = JsonConvert.SerializeObject(report, Formatting.Indented, new StringEnumConverter());
    context.Response.ContentType = MediaTypeNames.Application.Json;
    await context.Response.WriteAsync(result);
}
```

The exception I get from this `MyDependencyWebApi` is a `TaskCanceledException`: it sometimes times out. Even if I set the timeout higher, it still sometimes times out. The exception I get from that in the logs is this:

```
[18:29:31 ERR] Health check MyDependencyWebApi with status Unhealthy completed after 2117.2718ms with message 'null'
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: De I/O-bewerking is afgebroken vanwege het afsluiten van een thread of vanwege een opdracht van een toepassing..
 ---> System.Net.Sockets.SocketException (995): De I/O-bewerking is afgebroken vanwege het afsluiten van een thread of vanwege een opdracht van een toepassing.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.<CheckUsabilityOnScavenge>g__ReadAheadWithZeroByteReadAsync|45_0()
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at HealthChecks.Uris.UriHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken) in /_/src/HealthChecks.Uris/UriHealthCheck.cs:line 54
```

This results in a JSON like the one I listed in my initial post on the `/health` endpoint of the application. The UI background-thread picks up on that exception and is unable to parse the output because it expects a `string` rather than an `Exception` object structure. That stacktrace is also listed in my initial post.

Finally, these are the packages I with regard to healthchecks:

![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/5938204/3ef2a772-f613-44e9-81bd-416909c43604)

Hope this helps. If not, please let me know and I'll be happy to help out further (although I'm probably AFK during the weekend).

**Comment by sungam3r** [comment]
What if you remove `ResponseWriter = WriteHealthCheckFormattedResponse,` line? Default formatter from `HealthChecks.UI.Client.UIResponseWriter.WriteHealthCheckUIResponse` should work properly.

**Comment by rvanheest** [comment]
@sungam3r thanks for your response! This is what was missing from my implementation. It seems to work fine now. In my project the HealthChecksUI was added later than the healthchecks provided in this project, so I skipped the part of the documentation about the `ResponseWriter`. Thanks for your help!
