### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0

### ISSUE THREAD

**Issue by DaleyKD** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2084]
Please, fill the following sections to help us fix the issue

**What happened**:
```
fail: Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService[104]
      Health check azure_blob_storage threw an unhandled exception after 16.2131ms
      System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
      File name: 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
         at HealthChecks.Azure.Storage.Blobs.AzureBlobStorageHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at HealthChecks.Azure.Storage.Blobs.AzureBlobStorageHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
         at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.RunCheckAsync(HealthCheckRegistration registration, CancellationToken cancellationToken)
```

**What you expected to happen**:
I shouldn't need to manually add a reference to Microsoft.Bcl.AsyncInterfaces v7.0.0.0.

**How to reproduce it (as minimally and precisely as possible)**:
Add a health check for Azure Blob Storage.
Here are my package references:
```
    <PackageReference Include="AspNetCore.HealthChecks.Azure.Storage.Blobs" Version="7.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.AzureApplicationInsights" Version="7.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.AzureKeyVault" Version="7.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="7.0.1" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="7.0.13" />
```

``` csharp
// Configure Blob Service Client for use in Health Checks
services.AddAzureClients(x =>
{
    var azureStorageConnectionString = configuration.GetConnectionString("DataProtectionAzureStorage");
    var dataProtectionSection = configuration.GetSection("DataProtection");
    var azureStorageUriString = dataProtectionSection["StorageUri"];

    if (!string.IsNullOrEmpty(azureStorageConnectionString))
    {
        x.AddBlobServiceClient(azureStorageConnectionString);
    }
    else if (!string.IsNullOrWhiteSpace(azureStorageUriString))
    {
        x.AddBlobServiceClient(new Uri(azureStorageUriString));
        x.UseCredential(new DefaultAzureCredential());
    }
});

services.AddHealthChecks().AddAzureBlobStorage();
```

**Source code sample**:

**Anything else we need to know?**:

**Environment**:

- .NET Core version: 7.0
- Healthchecks version: 7.0
- Operative system: Windows 11
- Others:

**Comment by insylogo** [comment]
Same issue here. Shouldn't need Microsoft.Bcl.AsyncInterfaces with dotnet 7 or later, but it's coming up for me when using blob storage health checks.

**Comment by blogcraft** [comment]
Same problem here... :/

**Comment by DaleyKD** [comment]
I could be wrong, but I upgraded to .NET 8 today (as much as I could). In doing so, I no longer needed a reference to this. Something must have updated it's dependency. I didn't take any additional time to investigate.

**Comment by blogcraft** [comment]
🦖 Didn't know it was already out! Well, I will test it and see what happens.

**Comment by DaleyKD** [comment]
@blogcraft  - Today is .NET 8 Release Day. https://www.dotnetconf.net/

**Comment by sungam3r** [comment]
#2109

**Comment by sungam3r** [comment]
Additional info here https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/1724#issuecomment-1469583112 and below.
