### ISSUE TITLE
AspNetCore.HealthCheck.SqlServer wrong connection string format error

### ISSUE THREAD

**Issue by FranksUH** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2138]
I have a new project using .Net 8 I currently have installed **AspNetCore.HealthCheck.SqlServer** 8.0.0 and use it like this:

```
 services.AddHealthChecks()
     .AddSqlServer(new SqlServerHealthCheckOptions
     {
         ConnectionString = connectionsConfig.ConnectionDB
     })
     .AddApplicationInsightsPublisher(connectionsConfig.ApplicationInsightsInstrumentationKey, true);
```
     
   When the application starts I have the following exception in the console:
   
Health check HealthChecks.Publisher.ApplicationInsights.ApplicationInsightsPublisher threw an unhandled exception after 19.2681ms
System.ArgumentException: There was an error parsing the Connection String: Input contains invalid delimiters and cannot be parsed. Expected example: 'key1=value1;key2=value2;key3=value3'.
 ---> System.ArgumentException: Input contains invalid delimiters and cannot be parsed. Expected example: 'key1=value1;key2=value2;key3=value3'.
   at Microsoft.ApplicationInsights.Extensibility.Implementation.ConfigString.ConfigStringParser.Parse(String configString)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints.EndpointProvider.ParseConnectionString(String connectionString)
   --- End of inner exception stack trace ---
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints.EndpointProvider.ParseConnectionString(String connectionString)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints.EndpointProvider.set_ConnectionString(String value)
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.set_ConnectionString(String value)
   at HealthChecks.Publisher.ApplicationInsights.ApplicationInsightsPublisher.GetOrCreateTelemetryClient() in /_/src/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisher.cs:line 115
   at HealthChecks.Publisher.ApplicationInsights.ApplicationInsightsPublisher.PublishAsync(HealthReport report, CancellationToken cancellationToken) in /_/src/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisher.cs:line 42
   at Microsoft.Extensions.Diagnostics.HealthChecks.HealthCheckPublisherHostedService.RunPublisherAsync(IHealthCheckPublisher publisher, HealthReport report, CancellationToken cancellationToken)
   

This is the format of my connection string:

**Server=xxx.database.windows.net;Initial Catalog=xxx;Persist Security Info=False;User ID=xxx-xxx;Password=xxx;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;**

**Comment by FranksUH** [comment]
I just found the issue but it was not intuitive at all because even when the error message says: **There was an error parsing the Connection String** and removing the line "AddSqlServer" the error message disappears, the connection string to the database was fine, the one that was wrong was the connection to Application Insights. So the solution was just to change this:

` .AddApplicationInsightsPublisher(connectionsConfig.ApplicationInsightsInstrumentationKey, true);`
 
 for this:
 
`  .AddApplicationInsightsPublisher(connectionsConfig.ApplicationInsightsConnectionString, true);`
