### ISSUE TITLE
healthchecksdb file permission error

### ISSUE THREAD

**Issue by sadeghhp** [Xabaril/AspNetCore.Diagnostics.HealthChecks#22]
Hi
i have a problem with healthchecksdb file ! 
how can i config the location of this file to make right permissions ?

`Application startup exception: System.AggregateException: One or more errors occurred. (Access to the path 'C:\apps\healthchecksdb' is denied.) ---> System.UnauthorizedAccessException: Access to the path 'C:\apps\healthchecksdb' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.DeleteAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureDeletedAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.CreateDatabase(IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---`

**Comment by unaizorrilla** [comment]
Hi sadeghhp,

can you check the permissions as @CarlosLanderas write in the above comment?

**Comment by CarlosLanderas** [comment]
Storage providers feature has been implemented in UI version 3.1.1-preview1. 
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/455#issuecomment-613093369
