### ISSUE TITLE
DB support other than SqLite for healthchecksdb

### ISSUE THREAD

**Issue by uchetfield** [Xabaril/AspNetCore.Diagnostics.HealthChecks#226]
It would be nice if we could specify the DB provider that is utilized when storing the health checks.  Instead of using a Sqlite db all the time it would be nice if we could specify a SqlServer or a different DB provider that could be utilized for storing the health checks.

**Comment by CarlosLanderas** [comment]
Ping @unaizorrilla

**Comment by kevbite** [comment]
It would be great if this could have an extension point so that other people could build the alternative database support. Would love if this supported MongoDB.

**Comment by udlose** [comment]
@unaizorrilla can you please provide some guidance on extending to persist on another db - maybe SQL Server?

**Comment by Phillip9587** [comment]
Deployment on Azure Linux App Services is failing because of the SQLite Database!

**Error Log**

2020-03-09T20:05:54.344970768Z: [INFO] Failed executing DbCommand (30,045ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
2020-03-09T20:05:54.344982269Z: [INFO] PRAGMA journal_mode = 'wal';
2020-03-09T20:05:54.448764405Z: [ERROR] Unhandled exception. System.AggregateException: One or more errors occurred. (SQLite Error 5: 'database is locked'.)
2020-03-09T20:05:54.448807306Z: [ERROR] ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
2020-03-09T20:05:54.448818507Z: [ERROR] at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
2020-03-09T20:05:54.448827407Z: [ERROR] at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
2020-03-09T20:05:54.448836107Z: [ERROR] at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
2020-03-09T20:05:54.448846907Z: [ERROR] at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
2020-03-09T20:05:54.448855108Z: [ERROR] at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
2020-03-09T20:05:54.448863308Z: [ERROR] at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
2020-03-09T20:05:54.448883909Z: [ERROR] at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
2020-03-09T20:05:54.448892909Z: [ERROR] at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateAsync(CancellationToken cancellationToken)
2020-03-09T20:05:54.448901509Z: [ERROR] at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
2020-03-09T20:05:54.448909809Z: [ERROR] at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.CreateDatabase(IServiceProvider serviceProvider)
2020-03-09T20:05:54.448918010Z: [ERROR] --- End of inner exception stack trace ---
2020-03-09T20:05:54.448925810Z: [ERROR] at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2020-03-09T20:05:54.448933910Z: [ERROR] at System.Threading.Tasks.Task.Wait()
2020-03-09T20:05:54.448941810Z: [ERROR] at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddHealthChecksUI(IServiceCollection services, String databaseName, Action`1 setupSettings)
2020-03-09T20:05:54.448950411Z: [ERROR] at Sprengnetter.Wohnbau.Foerderungen.API.Startup.ConfigureServices(IServiceCollection services) in /home/vsts/work/1/s/Src/API/Startup.cs:line 121
2020-03-09T20:05:54.448958711Z: [ERROR] at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2020-03-09T20:05:54.448966811Z: [ERROR] at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2020-03-09T20:05:54.448975012Z: [ERROR] at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
2020-03-09T20:05:54.448984312Z: [ERROR] at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.g__Startup|0(IServiceCollection serviceCollection)
2020-03-09T20:05:54.448993112Z: [ERROR] at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
2020-03-09T20:05:54.449001012Z: [ERROR] at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.b__0(IServiceCollection services)
2020-03-09T20:05:54.449009613Z: [ERROR] at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
2020-03-09T20:05:54.449017713Z: [ERROR] at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.b__0(HostBuilderContext context, IServiceCollection services)
2020-03-09T20:05:54.449026413Z: [ERROR] at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
2020-03-09T20:05:54.449034013Z: [ERROR] at Microsoft.Extensions.Hosting.HostBuilder.Build()
2020-03-09T20:05:54.463305772Z: [ERROR] at Sprengnetter.Wohnbau.Foerderungen.API.Program.Main(String[] args) in /home/vsts/work/1/s/Src/API/Program.cs:line 18
2020-03-09T20:05:54.504346591Z: [ERROR] ptrace(ATTACH, 29) FAILED Operation not permitted
2020-03-09T20:05:54.506025945Z: [INFO] Writing minidump with heap to file /home/logs/dumps/coredump.64c36a8a0b68.29.1583784314

2020-03-09T20:05:55.111801018Z: [ERROR] /opt/startup/startup.sh: line 11: 29 Aborted (core dumped) dotnet /home/site/wwwroot/Sprengnetter.Wohnbau.Foerderungen.API.dll
2020-03-09T20:05:55.112748549Z: [INFO] WARNING: Startup command execution failed with exit code 134
2020-03-09T20:05:55.113286166Z: [INFO] Running the default application instead...
2020-03-09T20:05:55.721693024Z: [INFO] Hosting environment: Production
2020-03-09T20:05:55.737878144Z: [INFO] Content root path: /defaulthome/hostingstart/
2020-03-09T20:05:55.738006148Z: [INFO] Now listening on: http://[::]:8080
2020-03-09T20:05:55.738211955Z: [INFO] Application started. Press Ctrl+C to shut down.

**Comment by CarlosLanderas** [comment]
Storage providers feature has been implemented in UI version 3.1.1-preview1. 
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/455#issuecomment-613093369

**Comment by udlose** [comment]
@CarlosLanderas  is there a plan to add support for MySql?

**Comment by CarlosLanderas** [comment]
Yes, as soon as netcore 3.1 is supported:
https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core.html
