### ISSUE TITLE
Compatibility issue with MongoDB.Driver 3.0.0

### ISSUE THREAD

**Issue by ChrisDox** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2322]
I have issue with last mongoDB.Driver 3.0.0

System.IO.FileNotFoundException: Could not load file or assembly 'MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321'. The system cannot find the file specified.
2024-11-24T18:30:59.8559813Z
2024-11-24T18:30:59.8559841Z       File name: 'MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321'
2024-11-24T18:30:59.8563412Z          at HealthChecks.MongoDb.MongoDbHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
2024-11-24T18:30:59.8563494Z          at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.RunCheckAsync(HealthCheckRegistration registration, CancellationToken cancellationToken)

**Comment by eerhardt** [comment]
Thanks for the feedback. I'm in the middle of making the same change as [Add support for RabbitMQ.Client version 7. (Xabaril/AspNetCore.Diagnostics.HealthChecks#2323)](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2323), but for MongoDB.Driver. Using the same strategy as that PR - splitting the package into 2 - one for each major version.
