### ISSUE TITLE
AspNetCore.Healthchecks.Oracle health check swallows exception

### ISSUE THREAD

**Issue by tpao** [Xabaril/AspNetCore.Diagnostics.HealthChecks#282]
I am using the AspNetCore.Healthchecks.Oracle health check as follows in my Startup.cs
``public void ConfigureServices(IServiceCollection services)
        {
services.AddHealthChecks()
                .AddOracle(DbConnectionString, name:"Auth DB Health Check");
}``

and I made a typo in my connection string and the health check fails but because the exception is swallowed it made this difficult to debug. The unhealthy health check displayed in the log as:

fail: Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService[103]
      Health check Auth DB Health Check completed after 896.8707ms with status Unhealthy and '(null)'

**Comment by tpao** [comment]
By the way, I was able to get the underlying exception thrown by Oracle Managed Client just in case it is needed.

Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-12545: Network Transport: Unable to resolve connect hostname
 ---> OracleInternal.Network.NetworkException (0x80004005): ORA-12545: Network Transport: Unable to resolve connect hostname
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at OracleInternal.Network.TcpTransportAdapter.Connect(ConnectionOption conOption)
   at OracleInternal.Network.OracleCommunication.DoConnect(String tnsDescriptor)
   at OracleInternal.Network.OracleCommunication.Connect(String tnsDescriptor, Boolean doNAHandshake, String IName, ConnectionOption CO)
   at OracleInternal.ServiceObjects.OracleConnectionImpl.Connect(ConnectionString cs, Boolean bOpenEndUserSession, OracleConnection connRefForCriteria, String instanceName)
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
   at Oracle.ManagedDataAccess.Client.OracleConnection.Open()
   at Blizzard.Oracle.Connection.OracleConnection.Open()
   at Blizzard.Oracle.Connection.OracleConnectionManager.GetConnection()
   at Blizzard.Oracle.Querying.QueryOperation..ctor(IOracleConnectionManager oracleConnectionManager, IOracleCommandFactory oracleCommandFactory, ITranslationHelper translationHelper, ISqlTracer tracer)
   at Blizzard.Oracle.Querying.QueryOperation..ctor(IOracleConnectionManager oracleConnectionManager, ISqlTracer tracer)
   at Blizzard.Oracle.Factories.OracleQueryOperationFactory.GetOracleQueryOperation()
   at Blizzard.Oracle.Querying.OracleQueryHelper.GetListAsync[T](String sqlCommand, List`1 parameters, Func`2 translate)
   at DataProtection.DataProtectionService.Repositories.RequestRepository.GetApplicationDefinitionsAsync() in E:\Workspace-Git\DataProtection.DataProtectionService\DataProtection.DataProtectionService\Repositories\RequestRepository.cs:line 39
   at DataProtection.DataProtectionService.Managers.RequestManager.GetApplicationDefinitionAsync(String applicationId) in E:\Workspace-Git\DataProtection.DataProtectionService\DataProtection.DataProtectionService\Managers\RequestManager.cs:line 35
   at DataProtection.DataProtectionService.Controllers.DataProtectionController.GetPendingProcesses(GetPendingProcessesRequest request) in E:\Workspace-Git\DataProtection.DataProtectionService\DataProtection.DataProtectionService\Controllers\DataProtectionController.cs:line 32
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by unaizorrilla** [comment]
Hi @tpao 

Oracle healthcheck is honoring the exception message right now

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/b31936bed18f33f8f3c1dd65180911b6affbd92a/src/HealthChecks.Oracle/OracleHealthCheck.cs#L36

**Comment by BibhutiBhusanDora** [comment]
How do I enable this logging ?? Using Serilog.
