### ISSUE TITLE
.NET Core 3.0 + Docker + Kubernetes, Error on Application Start Up. 

### ISSUE THREAD

**Issue by Grey007** [Xabaril/AspNetCore.Diagnostics.HealthChecks#286]
Hi there, 

I am busy migrating my application from core 2.2 to core 3.0 and getting the following error on application startup: 

> GetHealthReport threw an exception when trying to get report from http:\/\/localhost:44350\/healthz configured with name Application Health

I'm not too sure why it's failing as it works locally. Here is my code: 

```
private static void ConfigureAppServices(IServiceCollection services)
   {
            services.AddControllers();
            services.AddHealthChecksUI();
            services.AddHealthChecks()
               .AddCheck("self", () => running ? HealthCheckResult.Healthy()
                                    : HealthCheckResult.Unhealthy())
                .AddSqlServer(Sql, tags: new[] { "services" })
                .AddOracle(Orale, tags: new[] { "services" })                   
   }
```
```
 public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
        {
           
            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHealthChecks("/healthz", new HealthCheckOptions
                {
                   Predicate = _ => true,
                   ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
                );
                endpoints.MapHealthChecks("/self", new HealthCheckOptions
                {
                    Predicate = r => r.Name.Contains("self")
                });
                endpoints.MapHealthChecks("/ready", new HealthCheckOptions
                {
                    Predicate = r => r.Tags.Contains("services")
                });
                endpoints.MapHealthChecksUI();
                endpoints.MapControllers();

            });
        }
```
app.settings file:

```
  "HealthChecks-UI": {
    "HealthChecks": [
      {
        "Name": "Application Health",
        "Uri": "http://localhost:44350/healthz"
        //"Uri": "http://vault-dev.vault-dev.svc.cluster.local:443/healthz"
      }
    ],
...
```

Any suggestions as to what I am doing wrong?

**Comment by CarlosLanderas** [comment]
Hello. Remember the application is running in port 80 in Kubernetes, not in 44350. You should change that in appsettings.json or use endpoint configuration by code when using AddHealthchecks(setup)

**Comment by Grey007** [comment]
That didn't work. Still got the same error. Is it still http://localhost:80? Or should I be using the service?

**Comment by CarlosLanderas** [comment]
You should use the Kubernetes service name for the target healthchecks endpoint.

That name of the service exposing the deployment is the one that will address your request to a pod.

Use 80 or 443 depending on your remote endpoint configuration.

**Comment by aiscrim** [comment]
I have a similar behavior. When I host my app in IIS everything works fine, but when I deploy it to Kubernetes it works for a while and after some minutes it gives that error.
I tried using both the localhost:80 and the Kubernetes service address, and I get the same results.

At startup I receive the following error, but then the healthchecks are shown correctly:

> [14:06:24 ERR] GetHealthReport threw an exception when trying to get report from <health checks uri> configured with name Local.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
at Newtonsoft.Json.JsonTextReader.ParseValue()
at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
at System.Net.Http.HttpResponseMessageExtensions.As[TContent](HttpResponseMessage response)
at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)
[14:06:24 WRN] The LINQ expression 'where [lf].HealthCheckName.Equals(__livenessName_0, InvariantCultureIgnoreCase)' could not be translated and will be evaluated locally.
[14:06:24 WRN] The LINQ expression 'Take(__p_1)' could not be translated and will be evaluated locally.
[14:06:24 WRN] The LINQ expression 'SingleOrDefault()' could not be translated and will be evaluated locally.

Then after ~15 minutes I start receiving this other error and healthchecks are in red:

> [14:24:09 ERR] GetHealthReport threw an exception when trying to get report from <health checks uri> configured with name Local.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SocketsHttpHandler'.
at System.Net.Http.SocketsHttpHandler.CheckDisposed()
at System.Net.Http.SocketsHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)

**Comment by xico002** [comment]
> That didn't work. Still got the same error. Is it still http://localhost:80? Or should I be using the service?
> 
> Also, if your application is Dockerized then your port will be whatever you may have exposed in the docker file.



> You should use the Kubernetes service name for the target healthchecks endpoint.
> 
> That name of the service exposing the deployment is the one that will address your request to a pod.
> 
> Use 80 or 443 depending on your remote endpoint configuration.

I couldn't quite understand this fully.
Let's assume I have a service called "service" and have an ingress with a host "host". How should I configurate my endpoint. Because right now I can run my pod successfully but when I try to access my api through my "host" it gives me nginx 502 bad gateway. But I can clearly see in the logs that the pod is running and giving me healthy or unhealthy status foreach endpoint I have. Also, If I do a portforward to my service that is running in azure cloud I can access my api and see swagger and healthchecks ui and everything. But if I access through the host it gives me the error I just mentioned. Can someone explin me this please?
