### ISSUE TITLE
Ignore certificate validaton

### ISSUE THREAD

**Issue by cheesi** [Xabaril/AspNetCore.Diagnostics.HealthChecks#289]
Hey!

I'm facing a problem with the healthchecks ui, which needs to load the healtchecks from a server with a self-signed certificate.

I thought this code would solve the problem, however, i still get an exception. The "Certificate check called!" is **NOT** printed to the console, it seems like it doesn't get called. The HealthCheck.UI seems to use the right HttpClient, as the `BaseAddress` configuration works. Seems really strange.
```csharp
services.AddHttpClient("health-checks", client =>
{
	client.BaseAddress = new Uri(_Configuration.GetValue<string>("Kestrel:Endpoints:Default:Url").Replace("*", "localhost"));
}).ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler()
{
	ClientCertificateOptions = ClientCertificateOption.Manual, //not needed, default
	ServerCertificateCustomValidationCallback = (httpRequestMessage, cert, cetChain, policyErrors) =>
	{
		Console.WriteLine("Certificate check called!");
		return true;
	}
});
```

Exception:
```csharp
HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      GetHealthReport threw an exception when trying to get report from /api/health configured with name testService.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)
```

System info: Latest Windows 10, .NET Core 3.0, Latest nuget package

Any idea, what's wrong here?

BR Christian

**Comment by unaizorrilla** [comment]
Let me check on this today!

**Comment by CarlosLanderas** [comment]
Hello. Please use the setup method to use a custom http handler.

Sample:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/test/FunctionalTests/HealthChecks.UI/Configuration/UIConfigurationTests.cs#L171

**Comment by cheesi** [comment]
Thanks, that works!

**Comment by xico002** [comment]
> Thanks, that works!

Hi @cheesi 
How did you apply it to your code?

**Comment by cheesi** [comment]
I ended up with something like this:
`
services.AddHealthChecksUI(setupSettings: setup =>
{
	setup.UseApiEndpointHttpMessageHandler(sp =>
	{
		return new HttpClientHandler
		{
			ServerCertificateCustomValidationCallback = (httpRequestMessage, cert, certChain, policyErrors) =>
			{
				//custom certificate validation check
				return true;
				return false;
			}
		};
	});
});
services.AddHttpClient("health-checks", client =>
{
	client.BaseAddress = new Uri(_Configuration.GetValue<string>("Kestrel:Endpoints:Default:Url").Replace("*", "localhost"));
});
`
