### ISSUE TITLE
Json Parsing error

### ISSUE THREAD

**Issue by coshea** [Xabaril/AspNetCore.Diagnostics.HealthChecks#308]
Hi all,

I seem to be running into an issue where the healthcheck fails and then the entire service becomes unresponsive. It throws errors saying it can't parse the json and the only solution is to restart the service. I only get the issue after the service has been running for many days.

I am running an ASP.NET Core 2.2 Windows service. 

Below are the logs I am getting:
```json
2019-10-21 08:20:59.7007|100|INFO|System.Net.Http.HttpClient.health-checks.LogicalHandler|Start processing HTTP request GET http://localhost:5001/health 
2019-10-21 08:21:37.3898|100|INFO|System.Net.Http.HttpClient.health-checks.ClientHandler|Sending HTTP request GET http://localhost:5001/health 
2019-10-21 08:26:05.0956||ERROR|HealthChecks.UI.Core.HostedService.HealthCheckReportCollector|GetHealthReport threw an exception when trying to get report from http://localhost:5001/health configured with name HTTP-Api-Basic. 
System.Threading.Tasks.TaskCanceledException: The operation was canceled. 
---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request. 
---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)
2019-10-21 09:21:22.7833|100|INFO|System.Net.Http.HttpClient.health-checks.LogicalHandler|Start processing HTTP request GET http://localhost:5001/health 
2019-10-21 09:21:22.8043|100|INFO|System.Net.Http.HttpClient.health-checks.ClientHandler|Sending HTTP request GET http://localhost:5001/health 
2019-10-21 09:21:22.8043|101|INFO|System.Net.Http.HttpClient.health-checks.ClientHandler|Received HTTP response after 8.2046ms - InternalServerError 
2019-10-21 09:21:22.8043|101|INFO|System.Net.Http.HttpClient.health-checks.LogicalHandler|End processing HTTP request after 32.181ms - InternalServerError 
2019-10-21 09:21:22.8189||ERROR|HealthChecks.UI.Core.HostedService.HealthCheckReportCollector|GetHealthReport threw an exception when trying to get report from http://localhost:5001/health configured with name HTTP-Api-Basic. 
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at System.Net.Http.HttpResponseMessageExtensions.As[TContent](HttpResponseMessage response)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)
```

Startup method looks like this:
```c#
services.AddHealthChecks();
services.AddHealthChecksUI();

services.AddHealthChecks()
	.AddSqlServer(
		x => x.GetRequiredService<IDbConnectionFactory>()
			.GetConnectionString(DatabaseConnectionName.RT), null,
		"sql server - RT", null, new[] { "db", "sql", "sqlserver" });

services.AddHealthChecks()
	.AddSqlServer(
		x => x.GetRequiredService<IDbConnectionFactory>()
			.GetConnectionString(DatabaseConnectionName.PT), null,
		"sql server - PT", null, new[] { "db", "sql", "sqlserver" });

Uri crystalReportUri = new Uri(Configuration.GetValue<string>("AppSettings:CrystalReportServer"));
services.AddHealthChecks()
	.AddUrlGroup(crystalReportUri, "crystal report server", null, new[] {"reporting", "crystal report" });
```

Configure method looks like this:
```c#
app.UseHealthChecks("/health", new HealthCheckOptions()
{
     Predicate = _ => true,
     ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
});
app.UseHealthChecksUI();
```

 And my appsettings.json file:

```json
"HealthChecksUI": {
    "HealthChecks": [
      {
        "Name": "HTTP-Api-Basic",
        "Uri": "http://localhost:5001/health"
      }
    ],
    "EvaluationTimeInSeconds": 300,
    "MinimumSecondsBetweenFailureNotifications": 300
  }
```
 Any help would be appreciated!

**Comment by CarlosLanderas** [comment]
Can you show your UI endpoint configurations? As I do not see them in code I guess you have them in appsettings.json

Thanks

**Comment by coshea** [comment]
Here is the settings in my appsettings.json file:
```json
"HealthChecksUI": {
    "HealthChecks": [
      {
        "Name": "HTTP-Api-Basic",
        "Uri": "http://localhost:5001/health"
      }
    ],
    "EvaluationTimeInSeconds": 300,
    "MinimumSecondsBetweenFailureNotifications": 300
  }
```

Thanks

**Comment by CarlosLanderas** [comment]
@coshea , are you configuring healthchecks and ui in the same application?

I see services.AddHealthChecks()
but I do not see any healthcheck configured if you are running the UI and the healthchecks in the same endpoint

**Comment by coshea** [comment]
@CarlosLanderas Here are the 3 healthchecks I use

```c#
services.AddHealthChecks()
	.AddSqlServer(
		x => x.GetRequiredService<IDbConnectionFactory>()
			.GetConnectionString(DatabaseConnectionName.RT), null,
		"sql server - RT", null, new[] { "db", "sql", "sqlserver" });

services.AddHealthChecks()
	.AddSqlServer(
		x => x.GetRequiredService<IDbConnectionFactory>()
			.GetConnectionString(DatabaseConnectionName.PT), null,
		"sql server - PT", null, new[] { "db", "sql", "sqlserver" });

Uri crystalReportUri = new Uri(Configuration.GetValue<string>("AppSettings:CrystalReportServer"));
services.AddHealthChecks()
	.AddUrlGroup(crystalReportUri, "crystal report server", null, new[] {"reporting", "crystal report" });
```

Thanks

**Comment by CarlosLanderas** [comment]
@coshea why are you using AddHealthchecks twice?

```csharp
services.AddHealthChecks();
services.AddHealthChecksUI();

services.AddHealthChecks()
	.AddSqlServer(
```

Sorry in order to help you I need to test the sample uploaded to some repository

**Comment by KevinKrueger** [comment]
Hi, why closed?
I have the same problem!

Exception:
GetHealthReport threw an exception when trying to get report from http://localhost:5000/api/health configured with name ......

Trace:
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReportAsync(HealthCheckConfiguration configuration) in /_/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 129
