### ISSUE TITLE
HealthCheck UI in docker doesn't display healthy status of service when first status is failuse

### ISSUE THREAD

**Issue by MaxShoshin** [Xabaril/AspNetCore.Diagnostics.HealthChecks#403]
I'm using docker image for hosting HealthCheckUI.
Image: xabarilcoding/healthchecksui:3.0.3 
It is latest now.

I start healthcheck ui container first.
It tries to get healthcheck info of my not started application (display unhealthy status in UI - it is ok).
Then i start my application (it is healthy now).
Unhelathy status in UI of my service is not updated (see following error for details). 

It seems that container contains outdated code.

```
fail: HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService[0]
      HealthCheck collector HostedService throw a error: The given key 'Endpoint' was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key 'Endpoint' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.SaveExecutionHistoryEntries(UIHealthReport healthReport, HealthCheckExecution execution, DateTime lastExecutionTime) in /src/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 196
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.SaveExecutionHistory(HealthCheckConfiguration configuration, UIHealthReport healthReport) in /src/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 129
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.Collect(CancellationToken cancellationToken) in /src/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 70
   at HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService.ExecuteAsync(CancellationToken cancellationToken) in /src/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollectorHostedService.cs:line 61
```

**Comment by sadedil** [comment]
Same issue here,

We are using K8s liveness probes. When the pod restarted once, Healthcheck UI can't find the new pod anymore. In the UI we started to see `Endpoint, Unhealthy, Connection refused` messages.

When i restart the `xabarilcoding/healthchecksui:3.0.3` pod, it's started to working as expected.

**Comment by CarlosLanderas** [comment]
I'll take a look!. However, we are gonna release the k8s operator soon, that will handle all the heavy work for you.

Check this video

https://twitter.com/Carlos_Lande/status/1223594881186258944?s=19

**Comment by sadedil** [comment]
Thanks for the answer, k8s operator will be nice.

But I want to ask something else. At the releases page i show the _3.0.0-ugrade-ui-3.0.9_, but when i checked the [docker hub](https://hub.docker.com/r/xabarilcoding/healthchecksui/tags) still see the 3.0.3.

Am I missing something?

**Comment by CarlosLanderas** [comment]
@MaxShoshin @sadedil  you are right. This issue was fixed. Let me publish the latest verison of the UI that will be the version 3.0.10

**Comment by CarlosLanderas** [comment]
Version 3.0.10 has been published. If you have any issue re-open the issue again.
Thanks!

**Comment by sadedil** [comment]
Hi @CarlosLanderas,

The problem seems solved, thank you.

**Comment by CarlosLanderas** [comment]
Thanks for the feedback @sadedil  :)
