### ISSUE TITLE
SQLite Error 10

### ISSUE THREAD

**Issue by Odonno** [Xabaril/AspNetCore.Diagnostics.HealthChecks#462]
**What happened**:

I got this exception today (not sure if it happened just now or several days ago).

![image](https://user-images.githubusercontent.com/6053067/77148794-8a849100-6a90-11ea-9faa-4219c9c47984.png)

I don't know what happened. It happened suddenly without us doing anything. I redeployed my app in order to fix this issue. I hope there is a fix for that.

Thank you.

**Environment**:

- .NET Core version : .NET Core 3.1.1 X86 v4.0.0.0 
- Healthchecks version 
<PackageReference Include="AspNetCore.HealthChecks.Hangfire" Version="3.0.0" />
<PackageReference Include="AspNetCore.HealthChecks.SignalR" Version="3.0.0" />
<PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="3.0.0" />
<PackageReference Include="AspNetCore.HealthChecks.UI" Version="3.0.9" />
<PackageReference Include="AspNetCore.HealthChecks.Uris" Version="3.0.0" />

- Operative system: Microsoft Windows 10.0.14393 (Azure App Service)
- Others: Microsoft.AspNetCore.Hosting version 3.1.1-servicing.19615.10 

**More details**

If you want more details about the exception, here it is:

```
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 10: 'disk I/O error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.CreateDatabase(IServiceProvider serviceProvider)
```

**Comment by unaizorrilla** [comment]
You continue with this error?

**Comment by Odonno** [comment]
Not recently. I will check tomorrow.

**Comment by Odonno** [comment]
Still no error. Still don't know how this error happened. Anyway, I close the issue and will reopen it if it happen again.

**Comment by unaizorrilla** [comment]
Thanks a lot @Odonno !
