### ISSUE TITLE
AspNetCore.HealthChecks.Kafka v3.1.0 is not compatible with Confluent.Kafka v1.4.0 NuGet package

### ISSUE THREAD

**Issue by Dobby007** [Xabaril/AspNetCore.Diagnostics.HealthChecks#478]
**What happened**:
AspNetCore.HealthChecks.Kafka v3.1.0 is not compatible with Confluent.Kafka v1.4.0 NuGet package. An exception is thrown by the runtime. Seems like they modified the signature of ProduceAsync method. Here is a stack trace:
`2020-04-13 16:22:03.2194|ERROR|Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService|Health check kafka threw an unhandled exception after 0.3422ms
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Confluent.Kafka.DeliveryResult`2<!0,!1>> Confluent.Kafka.IProducer`2.ProduceAsync(System.String, Confluent.Kafka.Message`2<!0,!1>)'.
   at HealthChecks.Kafka.KafkaHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at HealthChecks.Kafka.KafkaHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.RunCheckAsync(IServiceScope scope, HealthCheckRegistration registration, CancellationToken cancellationToken)`

**Environment**:

- .NET Core version 3.1
- Healthchecks version 3.1
- Operative system: Linux

**Comment by unaizorrilla** [comment]
Hi @Dobby007 

I update to 1.4.0 the dependency of Kafka healthcheck, a new build is on appveyor, when finished a new package will be on nuget with version 3.1.1 and solve this issue.

Please close the issue if new package solve it!

**Comment by Dobby007** [comment]
It's working now. Thank you.
