### ISSUE TITLE
HealtChecks-UI Docker Image - Authorization issue with Azure App Configuration and Managed Identity Service

### ISSUE THREAD

**Issue by denisky** [Xabaril/AspNetCore.Diagnostics.HealthChecks#512]
I'm having an issue running the docker image with Azure App Configuration and Managed Identity Service.

I'm getting an errors when the application is loading.

> **2020-04-29T11:14:26.590139113Z Unhandled exception. System.ArgumentException: The configuration store with the endpoint 'https://*****.azconfig.io/' could not be found. (Parameter 'endpoint')**
2020-04-29T11:14:26.590176814Z    at Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.ManagedIdentityConnector.GetConnectionString(Uri endpoint, Permissions permissions, RequestOptions options, CancellationToken cancellationToken)
2020-04-29T11:14:26.590182614Z    at Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.AzconfigClientFactory.CreateClient(Uri endpoint, AzconfigClientFactoryOptions options, CancellationToken cancellationToken)
2020-04-29T11:14:26.590186514Z    at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationOptions.ConnectWithManagedIdentity(String endpoint)
2020-04-29T11:14:26.590189814Z    at HealthChecks.UI.Image.Extensions.AzureAppConfigurationSetup.WithManagedIdentity(AzureAppConfigurationOptions options) in /src/build/docker-images/HealthChecks.UI.Image/Extensions/IConfigurationBuilderExtensions.cs:line 41
2020-04-29T11:14:26.590194214Z    at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource.<>c__DisplayClass2_0.<.ctor>b__0()
2020-04-29T11:14:26.590198014Z    at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource.Build(IConfigurationBuilder builder)
2020-04-29T11:14:26.590201314Z    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
2020-04-29T11:14:26.590204314Z    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
2020-04-29T11:14:26.590207714Z    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
2020-04-29T11:14:26.591779822Z    at HealthChecks.UI.Image.Program.Main(String[] args) in /src/build/docker-images/HealthChecks.UI.Image/Program.cs:line 20

> **2020-04-29T11:45:28.989645955Z Unhandled exception. System.UnauthorizedAccessException: The specified user '' does not have the permissions required to access the configuration store.**
2020-04-29T11:45:28.989686656Z    at Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.ManagedIdentityConnector.GetConnectionString(Uri endpoint, Permissions permissions, RequestOptions options, CancellationToken cancellationToken)
2020-04-29T11:45:28.989692756Z    at Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.AzconfigClientFactory.CreateClient(Uri endpoint, AzconfigClientFactoryOptions options, CancellationToken cancellationToken)
2020-04-29T11:45:28.989696556Z    at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationOptions.ConnectWithManagedIdentity(String endpoint)
2020-04-29T11:45:28.997711096Z    at HealthChecks.UI.Image.Extensions.AzureAppConfigurationSetup.WithManagedIdentity(AzureAppConfigurationOptions options) in /src/build/docker-images/HealthChecks.UI.Image/Extensions/IConfigurationBuilderExtensions.cs:line 41
2020-04-29T11:45:28.997767896Z    at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource.<>c__DisplayClass2_0.<.ctor>b__0()
2020-04-29T11:45:28.997809796Z    at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource.Build(IConfigurationBuilder builder)
2020-04-29T11:45:28.997849996Z    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
2020-04-29T11:45:28.997863596Z    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
2020-04-29T11:45:28.997909697Z    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
2020-04-29T11:45:28.997926197Z    at HealthChecks.UI.Image.Program.Main(String[] args) in /src/build/docker-images/HealthChecks.UI.Image/Program.cs:line 20

Managed identity is enabled on the App Service
![image](https://user-images.githubusercontent.com/38464498/80594712-8766b400-89f1-11ea-84f7-0e6a4941134b.png)

I assigned the **App Configuration Data Reader** role to my identity.
![image](https://user-images.githubusercontent.com/38464498/80594875-ceed4000-89f1-11ea-8d8d-af5c5b291acf.png)
![image](https://user-images.githubusercontent.com/38464498/80595027-0e1b9100-89f2-11ea-8562-50abc2fd2a6e.png)

I also added the **Reader** role without success.

Adding the **Contributor** role seems to work, is it a normal behavior?

Thanks you,

**Comment by unaizorrilla** [comment]
Why this is related with healtchecks project? 

The excepcion throw on 

`Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource.Build(IConfigurationBuilder builder)`

Probably is better if you fill the issue on Azure App Configuration Repository

Thanks!

**Comment by denisky** [comment]
Hi,
I reported the issue here since you provide a feature using Azure App Configuration.
I wanted to know if it was a normal behavior or if you experienced that issue while testing the feature.

**Comment by CarlosLanderas** [comment]
@unaizorrilla this is a feature of the docker image. It is using an old package version. Let me review it and update it

**Comment by CarlosLanderas** [comment]
@denisky , latest docker image (5.0.0-preview1) updates to the latest Azure App Configuration package. The former version was extremely old. Please, give it a try and if you find some problem let us know
