### ISSUE TITLE
MySqlConnector 1.0.1 Rename MySql.Data.MySqlClient to  MySqlConnector  !

### ISSUE THREAD

**Issue by maikebing** [Xabaril/AspNetCore.Diagnostics.HealthChecks#609]
System.TypeLoadException: Could not load type 'MySql.Data.MySqlClient.MySqlConnection' from assembly 'MySqlConnector, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92'.          
|    at HealthChecks.MySql.MySqlHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
    at HealthChecks.MySql.MySqlHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)

**Comment by maikebing** [comment]
Need to wait upstream.
