### ISSUE TITLE
UI cause Exception when running in K8S

### ISSUE THREAD

**Issue by aminebizid** [Xabaril/AspNetCore.Diagnostics.HealthChecks#622]
My Config
```cs
 services.AddHealthChecks()
                .AddCheck("self", () => _running
                    ? HealthCheckResult.Healthy()
                    : HealthCheckResult.Unhealthy())
                .AddOracle(_configuration.GetConnectionString("Fredi"),
                    failureStatus: HealthStatus.Unhealthy,
                    timeout:TimeSpan.FromSeconds(3),
                    tags: new[] {"services"})
                .AddNpgSql(_configuration.GetConnectionString("DataTrust"),
                    failureStatus: HealthStatus.Unhealthy,
                    timeout:TimeSpan.FromSeconds(3),
                    tags: new[] {"services"})
                .AddAzureServiceBusSubscription(
                    _configuration["Bus:ConnectionString"],
                    _configuration["Bus:EntityPath"],
                    _configuration["Bus:SubscriptionName"],
                    failureStatus: HealthStatus.Degraded,
                    timeout:TimeSpan.FromSeconds(3),
                    tags: new[] {"services"});

  services.AddHealthChecksUI(setup =>
                {
                    setup.MaximumHistoryEntriesPerEndpoint(50);
                    setup.AddHealthCheckEndpoint("supplydata", "/healthz");
                    setup.SetEvaluationTimeInSeconds(60);
                    setup.SetMinimumSecondsBetweenFailureNotifications(120);
                })
                .AddInMemoryStorage();
```

```cs
  app.UseEndpoints(endpoints =>
            {
                endpoints.MapHealthChecks("healthz", new HealthCheckOptions()
                {
                    Predicate = _ => true,
                    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
                });
                endpoints.MapControllers();
                endpoints.MapHealthChecksUI();
            });
```

I get no Exception when running locally
But in K8S, I get this:

**[21:40:17 ERR] GetHealthReport threw an exception when trying to get report from /healthz configured with name supplydata.
System.Net.Http.HttpRequestException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'hostName')
 ---> System.ArgumentException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'hostName')**
   at System.Net.Dns.HostResolutionBeginHelper(String hostName, Boolean justReturnParsedIp, Boolean throwOnIIPAny, AsyncCallback requestCallback, Object state)
   at System.Net.Dns.BeginGetHostAddresses(String hostNameOrAddress, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.MultipleConnectAsync.StartConnectAsync(SocketAsyncEventArgs args, DnsEndPoint endPoint)
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)

**Comment by aminebizid** [comment]
Solved when using port 80

```cs
 services.AddHealthChecksUI(setup =>
                {
                    setup.MaximumHistoryEntriesPerEndpoint(50);
                    setup.AddHealthCheckEndpoint("supplydata", $"http://localhost/healthz");
                    setup.SetEvaluationTimeInSeconds(60);
                    setup.SetMinimumSecondsBetweenFailureNotifications(120);
                })
                .AddInMemoryStorage();
```

**Comment by CarlosLanderas** [comment]
@aminebizid  you can algo use:

**Comment by CarlosLanderas** [comment]
@aminebizid you can also use:

```csharp
  setup.AddHealthCheckEndpoint("supplydata", "/healthz");
```

And pass a valid dns name to ASPNETCORE_URLS environment variables (http/https://localhost) or using UseUrls kestrel extension method
