### ISSUE TITLE
Role Based Healthcheck API 

### ISSUE THREAD

**Issue by netcorenewbee** [Xabaril/AspNetCore.Diagnostics.HealthChecks#646]
I have a scenario where we created bunch of light healthcheck API endpoints( your basic Healthcheck application with URI set is app settings.json and return json object) and then one SQL enabled Healthcheck application that will read json results from these various API endpoints and display results using HealthchecksUI.  Only problem -  I can’t seem to find a way to only expose those Healthcheck api endpoints which the logged in user has access to. I’m using Windows  authentication and role based authorization from a sql server database.
**What would you like to be added**:
I was hoping to find a way to authorize these api endpoints in Configure method while binding the addhealthchecksUI. All the endpoint authorizations mentioned so far will only work on my individual light Healthcheck applications but not on the central one where I have roles setup and where they will be displayed.

**Why is this needed**:
Currently the Healthcheck API URI can only be configured in the appsettings.json or the ConfigureServices(), there is no way to control the access from the code anywhere else based on user roles.

**Comment by CarlosLanderas** [comment]
Hello, we are currently working to add OIDC Authentication and this will automatically configure endpoint authorization with default or custom policies

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/638

**Comment by netcorenewbee** [comment]
Hi Carlos, Thank you for the quick response! I stumbled upon this PR before but I wonder if it will help my case. 

For example my Central Health Check application may have 10 other healthcheck api's setup in its appsettings.json. The logged in user at any point may only have access to 4 out of the 10. Will the OIDC Authentication PR #638  help authenticate and authorize the each individual endpoints? 

I have policies in place and .RequireAuthorization is working great for all razor and healthchecksUI pages. But this is page level.

Do you have a time line for this rollout? I'm eager to test if it will fix my problem.

**Comment by CarlosLanderas** [comment]
@netcorenewbee take a look to the restrict access UI with OIDC sample that protects the endpoints.
You can actually create a policy that requires a role and use the RequireAuthentication on the MapHealthChecksUI endpoint

```csharp
 options.AddPolicy("RequireAdministratorRole",
             policy => policy.RequireRole("Administrator"));
```

```csharp
endpoints.MapHealthChecksUI().RequireAuthorization(RequireAdministratorRole);
```

**Comment by netcorenewbee** [comment]
Thank you, I will take a look today. This will however only restrict users to the HealthUI page itself it sounds like. Not to individual endpoints configured for UI. 

This is still a useful feature to provide some level of restriction.

**Comment by CarlosLanderas** [comment]
Hello! With that approach you protect all the UI resources. If you talk about the health endpoint themselves, those are an endpoint exposed by microsoft package and you can also use RequireAuthentication

**Comment by netcorenewbee** [comment]
When will this change be available in production and and what version of the HealthChecksUI do you recommend I download?

**Comment by CarlosLanderas** [comment]
@netcorenewbee  this is already available in versions for 3.1 and 5.0 in the UI package. This weekend I'll work to add it in the docker images. .NET 5.0 would be my choice :)

**Comment by dotnetshadow** [comment]
> 
> 
> Hello! With that approach you protect all the UI resources. If you talk about the health endpoints themselves (MapHealthchecks), those are an endpoints exposed by microsoft package and you can also use RequireAuthentication
> 
> I'm gonna update the sample

Hi there, firstly a great library, I tried the suggestion of restricting access to my endpoints as follows:

**appsettings.json**
```json
  "HealthChecksUI": {
    "HealthChecks": [
      {
        "Name": "HealthCheckTest",
        "Uri": "https://localhost:5101/health"
      }
    ],
    "EvaluationTimeOnSeconds": 10,
    "MinimumSecondsBetweenFailureNotifications": 60
  },
```

**configure**
```
app.UseEndpoints(endpoints =>
            {
               ....
                endpoints.MapHealthChecks("/health", new HealthCheckOptions
                {
                    Predicate = _ => true,
                    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
                });
                endpoints.MapHealthChecksUI().RequireAuthorization(Name.RequireRoleAdministrator);
                ....
});
```

**Error**                
But I always seem to get an error when calling **/healthchecks-api** `"Unexpected character encountered while parsing value: <. Path '', line 0, position 0."`

```json
[{"id":1,"status":"Unhealthy","onStateFrom":"2021-03-12T22:08:32.255956+11:00","lastExecuted":"2021-03-12T22:08:32.255956+11:00","uri":"https://localhost:5101/health","name":"HealthCheckStockWatch","discoveryService":null,"entries":[{"id":1,"name":"Endpoint","status":"Unhealthy","description":"Unexpected character encountered while parsing value: <. Path '', line 0, position 0.","duration":"00:00:00","tags":null}],"history":[]}]
```

If I check the `/health` url directly in the browser it all works correctly. The issue is only when **healthchecks ui** is trying to get access the endpoint,

When I check my logs I can see that the `/health` endpoint is trying to redirect to the login page when it's being called by healthcheck ui components. Even though I am logged in and have met the policy conditions, perhaps cookies aren't being flowed through when healthchecks ui is doing a http request?

```
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[12]
      AuthenticationScheme: Identity.Application was challenged.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:5101/health - - - 302 0 - 0.8555ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:5101/login/?ReturnUrl=%2Fhealth - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/Account/Login'
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[3]
      Route matched with {page = "/Account/Login", area = "Identity", action = "", controller = ""}. Executing page /Account/Login
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[101]
      Executing handler method StockWatch.Web.Areas.Identity.Pages.Account.LoginModel.OnGetAsync - ModelState is Valid
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[11]
      AuthenticationScheme: Identity.External signed out.
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[102]
      Executed handler method OnGetAsync, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[4]
      Executed page /Account/Login in 3.4285ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/Account/Login'
info: System.Net.Http.HttpClient.health-checks.ClientHandler[101]
      Received HTTP response headers after 6.1424ms - 200
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:5101/login/?ReturnUrl=%2Fhealth - - - 200 - text/html;+charset=utf-8 4.5483ms
info: System.Net.Http.HttpClient.health-checks.LogicalHandler[101]
      End processing HTTP request after 6.2486ms - 200
fail: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      GetHealthReport threw an exception when trying to get report from https://localhost:5101/health configured with name HealthCheckStockWatch.
      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
         at Newtonsoft.Json.JsonTextReader.ParseValue()
         at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
         at System.Net.Http.HttpResponseMessageExtensions.As[TContent](HttpResponseMessage response)
         at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)
info: HealthChecks.UI.Core.Notifications.WebHookFailureNotifier[0]
      Notification is sent on same window time.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      HealthReportCollector - health report execution history saved.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      HealthReport history already exists and is in the same state, updating the values.
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      HealthReportCollector has completed.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService[0]
      HealthCheck collector HostedService executed successfully.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService[0]
      Executing HealthCheck collector HostedService.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 5.0.3 initialized 'HealthChecksDb' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=HealthChecksUI
info: System.Net.Http.HttpClient.health-checks.LogicalHandler[100]
      Start processing HTTP request GET https://localhost:5101/health
info: System.Net.Http.HttpClient.health-checks.ClientHandler[100]
      Sending HTTP request GET https://localhost:5101/health
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:5101/health - -
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      RolesAuthorizationRequirement:User.IsInRole must be true for one of the following roles: (Administrator)
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[12]
      AuthenticationScheme: Identity.Application was challenged.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:5101/health - - - 302 0 - 0.4378ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:5101/login/?ReturnUrl=%2Fhealth - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/Account/Login'
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[3]
      Route matched with {page = "/Account/Login", area = "Identity", action = "", controller = ""}. Executing page /Account/Login
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[101]
      Executing handler method StockWatch.Web.Areas.Identity.Pages.Account.LoginModel.OnGetAsync - ModelState is Valid
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[11]
      AuthenticationScheme: Identity.External signed out.
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[102]
      Executed handler method OnGetAsync, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[4]
      Executed page /Account/Login in 4.1495ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/Account/Login'
info: System.Net.Http.HttpClient.health-checks.ClientHandler[101]
      Received HTTP response headers after 6.6242ms - 200
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:5101/login/?ReturnUrl=%2Fhealth - - - 200 - text/html;+charset=utf-8 5.6018ms
info: System.Net.Http.HttpClient.health-checks.LogicalHandler[101]
      End processing HTTP request after 6.718ms - 200
fail: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      GetHealthReport threw an exception when trying to get report from https://localhost:5101/health configured with name HealthCheckStockWatch.
      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
         at Newtonsoft.Json.JsonTextReader.ParseValue()
         at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
         at System.Net.Http.HttpResponseMessageExtensions.As[TContent](HttpResponseMessage response)
         at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)
info: HealthChecks.UI.Core.Notifications.WebHookFailureNotifier[0]
      Notification is sent on same window time.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      HealthReportCollector - health report execution history saved.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      HealthReport history already exists and is in the same state, updating the values.
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      HealthReportCollector has completed.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService[0]
      HealthCheck collector HostedService executed successfully.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService[0]
      Executing HealthCheck collector HostedService.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 5.0.3 initialized 'HealthChecksDb' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=HealthChecksUI
info: System.Net.Http.HttpClient.health-checks.LogicalHandler[100]
      Start processing HTTP request GET https://localhost:5101/health
info: System.Net.Http.HttpClient.health-checks.ClientHandler[100]
      Sending HTTP request GET https://localhost:5101/health
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:5101/health - -
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      RolesAuthorizationRequirement:User.IsInRole must be true for one of the following roles: (Administrator)
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[12]
      AuthenticationScheme: Identity.Application was challenged.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:5101/health - - - 302 0 - 0.3746ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:5101/login/?ReturnUrl=%2Fhealth - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/Account/Login'
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[3]
      Route matched with {page = "/Account/Login", area = "Identity", action = "", controller = ""}. Executing page /Account/Login
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[101]
      Executing handler method StockWatch.Web.Areas.Identity.Pages.Account.LoginModel.OnGetAsync - ModelState is Valid
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[11]
      AuthenticationScheme: Identity.External signed out.
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[102]
      Executed handler method OnGetAsync, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[4]
      Executed page /Account/Login in 2.2836ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/Account/Login'
info: System.Net.Http.HttpClient.health-checks.ClientHandler[101]
      Received HTTP response headers after 3.9541ms - 200
info: System.Net.Http.HttpClient.health-checks.LogicalHandler[101]
      End processing HTTP request after 4.0189ms - 200
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:5101/login/?ReturnUrl=%2Fhealth - - - 200 - text/html;+charset=utf-8 3.2157ms
fail: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      GetHealthReport threw an exception when trying to get report from https://localhost:5101/health configured with name HealthCheckStockWatch.
      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
         at Newtonsoft.Json.JsonTextReader.ParseValue()
         at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
         at System.Net.Http.HttpResponseMessageExtensions.As[TContent](HttpResponseMessage response)
         at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      HealthReportCollector - health report execution history saved.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      HealthReport history already exists and is in the same state, updating the values.
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      HealthReportCollector has completed.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService[0]
      HealthCheck collector HostedService executed successfully.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService[0]
      Executing HealthCheck collector HostedService.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 5.0.3 initialized 'HealthChecksDb' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=HealthChecksUI
info: System.Net.Http.HttpClient.health-checks.LogicalHandler[100]
      Start processing HTTP request GET https://localhost:5101/health
info: System.Net.Http.HttpClient.health-checks.ClientHandler[100]
      Sending HTTP request GET https://localhost:5101/health
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:5101/health - -
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      RolesAuthorizationRequirement:User.IsInRole must be true for one of the following roles: (Administrator)
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[12]
      AuthenticationScheme: Identity.Application was challenged.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:5101/health - - - 302 0 - 2.4950ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:5101/login/?ReturnUrl=%2Fhealth - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/Account/Login'
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[3]
      Route matched with {page = "/Account/Login", area = "Identity", action = "", controller = ""}. Executing page /Account/Login
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[101]
      Executing handler method StockWatch.Web.Areas.Identity.Pages.Account.LoginModel.OnGetAsync - ModelState is Valid
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[11]
      AuthenticationScheme: Identity.External signed out.
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[102]
      Executed handler method OnGetAsync, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[4]
      Executed page /Account/Login in 9.6115ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/Account/Login'
info: System.Net.Http.HttpClient.health-checks.ClientHandler[101]
      Received HTTP response headers after 17.9642ms - 200
info: System.Net.Http.HttpClient.health-checks.LogicalHandler[101]
      End processing HTTP request after 18.3279ms - 200
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:5101/login/?ReturnUrl=%2Fhealth - - - 200 - text/html;+charset=utf-8 13.7591ms
fail: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      GetHealthReport threw an exception when trying to get report from https://localhost:5101/health configured with name HealthCheckStockWatch.
      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
         at Newtonsoft.Json.JsonTextReader.ParseValue()
         at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
         at System.Net.Http.HttpResponseMessageExtensions.As[TContent](HttpResponseMessage response)
         at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)
info: HealthChecks.UI.Core.Notifications.WebHookFailureNotifier[0]
      Notification is sent on same window time.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      HealthReportCollector - health report execution history saved.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      HealthReport history already exists and is in the same state, updating the values.
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      HealthReportCollector has completed.
dbug: HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService[0]
      HealthCheck collector HostedService executed successfully.
```

**Comment by Capablanca4** [comment]
I'm facing a similar issue as @dotnetshadow : in my case I've simply added windows authentication (using the launchSettings.json) and I'm getting the following error in the logs :
```
System.Net.Http.HttpClient.health-checks.LogicalHandler: Information: Start processing HTTP request GET http://localhost:53204/health
System.Net.Http.HttpClient.health-checks.ClientHandler: Information: Sending HTTP request GET http://localhost:53204/health
System.Net.Http.HttpClient.health-checks.ClientHandler: Information: Received HTTP response headers after 5.5664ms - 401
System.Net.Http.HttpClient.health-checks.LogicalHandler: Information: End processing HTTP request after 23.8779ms - 401
```
@CarlosLanderas  do you have any clue why the credentials are not forwarded ? Is still someone working on this issue ?

**Comment by rogerskk** [comment]
I am also having the same issue as @dotnetshadow and @Capablanca4 . I have  
```
"iisSettings": {
    "windowsAuthentication": true,
    "anonymousAuthentication": false
}
```
in my launchsettings.json file and even though I can go directly to the /working path to see the correct json response, the /status for the HealthChecks UI gives the error: "Unexpected character encountered while parsing value: <. Path '', line 0, position 0."
If I set "anonymousAuthentication" to true then everything works as expected, but I would like to disable anonymous auth for the site.  I've tried using RequireAuthorization but nothing I've found online seems to make a difference.

**Comment by inexuscore** [comment]
Can someone please help me understand how I can require role-based authorization for JWT? I'm working on a solution with a REST API and the only authentication scheme is Bearer. I haven't found any documentation or content online; the only thing I can think of is using custom cookies. When an admin signs in, the app can register a cookie, and using a custom endpoint filter on the health checks route, read the cookie, validate, and authorize the request. Any guidance would be appreciated.
