### ISSUE TITLE
AddSqlLIteStorage and AddInMemoryStorage throw Exception on .NET Core 3.1 and EF 5.0

### ISSUE THREAD

**Issue by bakgerman** [Xabaril/AspNetCore.Diagnostics.HealthChecks#682]
Having issues using InMemory or SqlLite storage when changing from EF 3.1.10 to 5.0.
The issues occur using either .NET Core 3.1.10 or 5.0.

First Issue:

Calling services.AddHealthCheckUI.AddSqliteStorage throws the following Exception:

 Message=Method 'Create' in type 'Microsoft.EntityFrameworkCore.Sqlite.Query.Internal.SqliteQueryableMethodTranslatingExpressionVisitorFactory' from assembly 'Microsoft.EntityFrameworkCore.Sqlite, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
  Source=Microsoft.EntityFrameworkCore.Sqlite
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.SqliteServiceCollectionExtensions.AddEntityFrameworkSqlite(IServiceCollection serviceCollection)
   at Microsoft.EntityFrameworkCore.Sqlite.Infrastructure.Internal.SqliteOptionsExtension.ApplyServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>g__BuildServiceProvider|3()
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at HealthChecks.UI.Core.Data.HealthChecksDb..ctor(DbContextOptions`1 options)
...

This link seems relevant to the above Exception:
https://forums.asp.net/t/2166607.aspx?An+unhandled+exception+occurred+while+processing+the+request+

Second Issue:

Calling services.AddHealthCheckUI.AddInMemoryStorage throws the following Exception:
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Microsoft.Bcl.HashCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
  Source=HealthChecks.UI.Core
  StackTrace:
   at HealthChecks.UI.Core.Data.Configuration.HealthCheckExecutionEntryMap.Configure(EntityTypeBuilder`1 builder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration`1 configuration)
   at HealthChecks.UI.Core.Data.HealthChecksDb.OnModelCreating(ModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
...

Note this all worked for about a year on .NET Core 3.1 and EF 3.1.  The only change is upgrading to EF 5.0.

To reproduce:
           services.AddHealthChecksUI(
                setupSettings: setup =>
                    {
                        setup.AddHealthCheckEndpoint("BOLCISServices", "/health");

                        // Every 5 seconds
                        setup.SetEvaluationTimeInSeconds(5 * 60);
                        setup.SetMinimumSecondsBetweenFailureNotifications(5 * 60);

                        // 1 week of history every 5 seconds
                        setup.MaximumHistoryEntriesPerEndpoint(24 * 60 *7 / 5);
                    }
                ).AddInMemoryStorage(); or .AddInMemoryStorage();

Environment:
.NET Core 3.1.10 or 5.0.0 (both show the exceptions)
EF 5.0
AspNetCore.HealthChecks.UI 3.1.3
AspNetCore.HealthChecks.UI.InMemoryStorage 3.1.2
AspNetCore.HealthChecks.UI.SqlLiteSTorage 3.1.2
Windows 10 1909

Wondering at this point if EF 5.0 is badly broken in some way and I should go back to EF 3.1.10
There were no code changes done while encountering these issues, only change was updating EF.

**Comment by CarlosLanderas** [comment]
Hello @bakgerman 
Why are you using .NET Core 3.1 with EF 5.0? What is the use case?

I'm running the InMemory provider targeting net 5.0 and I do not have any problem,

**Comment by bakgerman** [comment]
Thanks, I will look into this on my end with a new empty solution and see where it got off track.

**Comment by bakgerman** [comment]
BTW EF Core 5.0 is supported on any .NET Standard 2.1 platform, so using that on .NET Core 3.1 is allowed.
EF Core 5.0 does not imply that it is tied to .NET 5.0.

See https://docs.microsoft.com/en-us/ef/core/what-is-new/

Also see https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes for breaking changes.

**Comment by CarlosLanderas** [comment]
We migrated all packages to net 5.0 (included healthchecks)
As we support asp.net core only we have moved on from netstandard in 5.0 branch. 

That might not be compatible

**Comment by bakgerman** [comment]
OK, I see: .NET 5.0 + EF 5.0 + Health Check 5.0 Preview works on my PC.
A mixture of versions does not.  Will close the issue.
