### ISSUE TITLE
Error in Blob Storage HealthCheck when access is granted at container level

### ISSUE THREAD

**Issue by kimbirkelund** [Xabaril/AspNetCore.Diagnostics.HealthChecks#741]
I'm using `AzureBlobStorageHealthCheck` with `DefaultAzureCredential` like so: `new AzureBlobStorageHealthCheck(blobContainerUri, new DefaultAzureCredential())` and deploying my app the an Azure App Service which has been configured to have the "Storage Blob Data Reader" role on the container the URI ponts to. In other word it does not have access to the container itself.

When used it this way the health check results in a very non obvious error:
```
The resource doesn't support specified Http Verb.
RequestId:5c5759af-801e-014e-807e-192cf9000000
Time:2021-03-15T09:32:03.8625693Z
Status: 405 (The resource doesn't support specified Http Verb.)
ErrorCode: UnsupportedHttpVerb

Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: 5c5759af-801e-014e-807e-192cf9000000
x-ms-client-request-id: a14fef49-c55d-4608-b726-4d72998189bd
x-ms-error-code: UnsupportedHttpVerb
Date: Mon, 15 Mar 2021 09:32:03 GMT
Allow: REDACTED
Content-Length: 237
Content-Type: application/xml


at Azure.Storage.Blobs.BlobRestClient.Service.GetPropertiesAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.Service.GetPropertiesAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, Nullable`1 timeout, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.GetPropertiesInternal(Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.GetPropertiesAsync(CancellationToken cancellationToken)
   at HealthChecks.AzureStorage.AzureBlobStorageHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
```

I'm guessing it is this line that is the issue: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/bfe43626199d82ecdedabf2b265ba84f089df736/src/HealthChecks.AzureStorage/AzureBlobStorageHealthCheck.cs#L44

I haven't time right now for more extensive testing, but I'll add more when I get the time.

**Comment by sungam3r** [comment]
Covered by #1372.
