### ISSUE TITLE
GetHealthReport threw an exception when trying to GetHealthReport(item) from an exception result

### ISSUE THREAD

**Issue by rafaarcangel** [Xabaril/AspNetCore.Diagnostics.HealthChecks#769]
Please, fill the following sections to help us fix the issue

**What happened**:
My health check throws an exception, and when GetReport tries to parse data, it fails.
![image](https://user-images.githubusercontent.com/19646006/117823774-20b7df80-b26e-11eb-8f66-cb1187c8eb37.png)

Here is the exception: 
```
fail: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
GetHealthReport threw an exception when trying to get the report from http://10.0.153.215:80/health/ready configured with name monitoring-digitaltwin-svc.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'entries['DigitalTwin Instance Models'].exception', line 1, position 115.
at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
at Newtonsoft.Json.JsonTextReader.ReadAsString()
at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
```
**What you expected to happen**:
Report right exception message.

**How to reproduce it (as minimally and precisely as possible)**:
Use this json string, catched from the service response:

```
{"entries":{"DigitalTwin Instance Models":{"data":{},"description":null,"duration":"00:00:00.0103582","exception":{"Status":403,"ErrorCode":null,"ClassName":"Azure.RequestFailedException","Message":"Service request failed.\nStatus: 403 (Forbidden)\n\nHeaders:\nStrict-Transport-Security: REDACTED\ntraceresponse: REDACTED\nDate: Tue, 11 May 2021 11:05:40 GMT\nContent-Length: 0\n","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Azure.DigitalTwins.Core.DigitalTwinModelsRestClient.ListAsync(IEnumerable`1 dependenciesFor, Nullable`1 includeModelDefinition, GetModelsOptions digitalTwinModelsListOptions, CancellationToken cancellationToken)\n   at Azure.DigitalTwins.Core.DigitalTwinsClient.<>c__DisplayClass38_0.<<GetModelsAsync>g__FirstPageFunc|0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()\n   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()\n   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()\n   at HealthChecks.AzureDigitalTwin.AzureDigitalTwinModelsHealthCheck.CheckModelResultAsync(HealthCheckContext context, DigitalTwinsClient digitalTwinClient, CancellationToken cancellationToken) in /src/DigitalTwin.Shared/HealthChecks/AzureDigitalTwinModelsHealthCheck.cs:line 63\n   at HealthChecks.AzureDigitalTwin.AzureDigitalTwinModelsHealthCheck.CheckModelResultAsync(HealthCheckContext context, DigitalTwinsClient digitalTwinClient, CancellationToken cancellationToken) in /src/DigitalTwin.Shared/HealthChecks/AzureDigitalTwinModelsHealthCheck.cs:line 63\n   at HealthChecks.AzureDigitalTwin.AzureDigitalTwinModelsHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken) in /src/DigitalTwin.Shared/HealthChecks/AzureDigitalTwinModelsHealthCheck.cs:line 51","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233088,"Source":"Azure.DigitalTwins.Core","WatsonBuckets":null},"status":1,"tags":["ready"]}},"status":1,"totalDuration":"00:00:00.0212366"}
```
- Healthchecks version latest
- Operative system: linux

**Comment by CarlosLanderas** [comment]
Can you paste the code?. You should not throw an exception, but a HealthCheckResult.Unhealthy

**Comment by rafaarcangel** [comment]
This is the services configuration:
```csharp
            services
                .AddHealthChecks()
                .AddAzureDigitalTwinModels(
                    configuration["DigitalTwin:ClientId"],
                    configuration["DigitalTwin:ClientSecret"],
                    configuration["TenantId"],
                    configuration["DigitalTwin:InstanceUrl"],
                    InstanceModel.GetAll(true).Select(m => m.SanitizedName).ToArray(),
                    $"{Constants.HealthChecks.NameDigitalTwin} Models",
                    HealthStatus.Degraded,
                    tags: new[] { "ready" })

```

And this is my healthcheck:
```csharp
        public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default)
        {
            try
            {
                if (!_digitalTwinClientConnections.TryGetValue(_clientId, out var digitalTwinClient))
                {
                    var credentials = new ClientSecretCredential(_tenantId, _clientId, _clientSecret);
                    digitalTwinClient = new DigitalTwinsClient(new Uri(_hostName), credentials);

                    if (!_digitalTwinClientConnections.TryAdd(_clientId, digitalTwinClient))
                    {
                        return new HealthCheckResult(context.Registration.FailureStatus, description: "No digital twin administration client connection can't be added into dictionary.");
                    }
                }

                return await CheckModelResultAsync(context, digitalTwinClient, cancellationToken);
            }
            catch (Exception ex)
            {
                return new HealthCheckResult(context.Registration.FailureStatus, exception: ex);
            }
        }

        private async Task<HealthCheckResult> CheckModelResultAsync(HealthCheckContext context, DigitalTwinsClient digitalTwinClient, CancellationToken cancellationToken)
        {
            var response = digitalTwinClient.GetModelsAsync(cancellationToken: cancellationToken);
            var models = new List<DigitalTwinsModelData>();
            await foreach (var model in response) models.Add(model);

            var unregistered = _models.Where(x => !models.Any(m => m.Id == x));
            var unmapped = models.Where(x => !_models.Contains(x.Id)).Select(x => x.Id);
            return unregistered.Any() || unmapped.Any()
                ? new HealthCheckResult(
                    context.Registration.FailureStatus,
                    "The digital twin is out of sync with the models provided",
                    null,
                    new Dictionary<string, object>()
                    {
                        [nameof(unregistered)] = unregistered,
                        [nameof(unmapped)] = unmapped
                    })
                : HealthCheckResult.Healthy();
        }

```

**Comment by t-l-k** [comment]
This is happening for me aswell, looks as if the HealthCheckReportCollector is calling the a service's healthcheck endpoint and attempting to convert the response directly into a `UIHealthReport` where `Exception` is `string`, not an object so the serializer fails. The diagnostic's assembly `HealthReport` class, `Exception` is an object. 

I would have thought it should call the service and expect a `HealthReport` response, then call static `UIHealthReport.CreateFrom(...)`

**Comment by t-l-k** [comment]
Okay I can see what's going on after having a bit of a dig. In short, the `HealthReport` class doesn't deserialize very gracefully. Hence why its preferable as per the samples in the repo to modify the format the response of the individual healthcheck endpoints as `UIHealthReport`, using the following preferred `ResponseWriter` configuration:

``` c#
config.MapHealthChecks("/healthz", new HealthCheckOptions
{
    Predicate = _ => true,
    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
});
```

Though not great if you have an estate of applications already emitting responses in the `HealthReport` format though. The next best option would be to introduce your own class matching very closely the serialization contract of `HealthReport` and its constituents, and use it as an intermediary serialization format in your UI healthcheck dashboard, as per this **_crude and incomplete_** example below which is just a rewrite of the `UIResponseWriter` behaviour above but executing in the context of the Healthchecks dashboard:

``` c# 
...
 services
     .AddTransient<CustomHealthReportDelegatingHandler>()
     .AddHealthChecksUI(setup => setup.UseApiEndpointDelegatingHandler<CustomHealthReportDelegatingHandler>())
...
```

``` c#
public class CustomHealthReport
{
    public Dictionary<String, HealthReportEntry> Entries { get; set; }

    public TimeSpan TotalDuration { get; set; }

    public HealthStatus Status { get; set; }
}

public class CustomHealthReportDelegatingHandler : DelegatingHandler
{
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        request.Headers.Add("Accept", new[] { "application/json" });

        var response = await base.SendAsync(request, cancellationToken);

        var customReport = await response.As<CustomHealthReport>();

        var report = new HealthReport(customReport.Entries, customReport.Status, customReport.TotalDuration);

        var uiReport = UIHealthReport.CreateFrom(report);

        var responseStream = new MemoryStream();

        await JsonSerializer.SerializeAsync(responseStream, uiReport, options.Value);
        responseStream.Position = 0;

        response.Content = new StreamContent(responseStream);

        return response;
    }
}
```

_Please note the sample is incomplete as `HealthReportEntry` does not deserialize gracefully, and that's where I stopped as I saw the truth of the matter._

**Comment by marcasmar94** [comment]
Any updates on this ?

**Comment by lzocateli** [comment]
The same thing is happening to me, do you have any updates on this?

**Comment by sungam3r** [comment]
nope

**Comment by zTranquilizer** [comment]
Very interesting, how to fix it in .net7?

**Comment by HamitKARAHAN** [comment]
I am also facing with same issue. Any updates??

**Comment by sungam3r** [comment]
Also note that Newtonsoft.Json lib was removed in favor of System.Text.Json in #1869 . Closing for now.
