### ISSUE TITLE
"The request matched multiple endpoints" when using MapHealthChecksUI

### ISSUE THREAD

**Issue by aleksvujic** [Xabaril/AspNetCore.Diagnostics.HealthChecks#797]
I am using **.NET Core 3.1**., `AspNetCore.HealthChecks.UI v3.1.3`, `AspNetCore.HealthChecks.UI.Client v3.1.2` and `AspNetCore.HealthChecks.UI.InMemory.Storage v3.1.2`. This is the code that I have currently:

`Startup.cs`
```cs
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services
            .AddHealthChecks()
            .AddCheck<ExternalServiceHealthCheck>("External service health check");
        
        services
            .AddHealthChecksUI()
            .AddInMemoryStorage();
    }

    public void Configure(IApplicationBuilder app)
    {
        app.UseStaticFiles();
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapHealthChecks("/health", new HealthCheckOptions()
	    {
                Predicate = _ => true,
                ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
            });
			
            endpoints.MapHealthChecksUI(setup =>
            {
                setup.UIPath = "/HealthChecks";
                setup.ApiPath = "/health";
            });
        });
    }
}
```

`ExternalServiceHealthCheck.cs`
```cs
public class ExternalServiceHealthCheck : IHealthCheck
{
    public Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default)
    {
        return Task.FromResult(HealthCheckResult.Healthy("External service is healthy"));
    }
}
```

When I manually go to `/health`, I get the following exception:

```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

Health checks
HealthChecks UI Api
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

When I go to `/HealthChecks`, I get the following error:

![image](https://user-images.githubusercontent.com/17112542/124273202-000a5880-db40-11eb-85f8-ffeca93272ba.png)

What am I doing wrong? I want to display all the registered health checks (`ExternalServiceHealthCheck` and others in the future) in the UI.

**Comment by sungam3r** [comment]
@aleksvujic Please try the latest v7 packages and reopen if this issue is still actual.
