### ISSUE TITLE
Error on AddSqliteStorage: SQLite Error 1: 'no such column: h.Tags'

### ISSUE THREAD

**Issue by jay-dev-9** [Xabaril/AspNetCore.Diagnostics.HealthChecks#801]
**What happened**:
- I try to add SQLite storage supports to my HealthChecksUI.
- I got this exception today: no such column: h.Tags

**Source code sample**:
```
services.AddHealthChecksUI(setup =>
            {
                setup.AddHealthCheckEndpoint("Self Health Check", "/health-ui-api");
                setup.MaximumHistoryEntriesPerEndpoint(20);
            }).AddSqliteStorage($"Data Source=DbFile/health-check-db.db");
```

If you want more details about the exception, here it is:

> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: h.Tags'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)

![image](https://user-images.githubusercontent.com/62498298/125265810-2ac68f00-e340-11eb-9967-5fb2c84765f3.png)

**Environment**:
- .NET Core version: 3.1
- Healthchecks version: 3.1.1
- Operative system: Windows 10 21H1
- Others:

**Comment by JackIT09** [comment]
To workaround the issue:
- Add column `Tags (TEXT)` to `HealthCheckExecutionEntries` table
- Then add this line:  `setup.DisableDatabaseMigrations();`
```
            services.AddHealthChecksUI(setup =>
            {
                setup.AddHealthCheckEndpoint("Self Health Check", "/health-ui-api");
                setup.MaximumHistoryEntriesPerEndpoint(20);
                setup.DisableDatabaseMigrations();
            }).AddSqliteStorage($"Data Source=DbFile/health-check-db.db");
```
