### ISSUE TITLE
Override redis port in healthcheck

### ISSUE THREAD

**Issue by JimmyLzy** [Xabaril/AspNetCore.Diagnostics.HealthChecks#807]
Hi team,
When using RedisHealthCheck library, the default port added is 6379, which causes connection issue below. But my reids port is 32969 and I can't change my server redis port. Are there any ways I can change the redis port setting in the library?

```
Health check redis-check completed after 11.5535ms with status Unhealthy and description '(null)'
      StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on redis://:password@host:32969:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.4.27433
         at StackExchange.Redis.ConnectionMultiplexer.ConnectImplAsync(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 879
         at HealthChecks.Redis.RedisHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
```

Thank you,
Jimmy

**Comment by JimmyLzy** [comment]
Find a way to fix the issue now. I need to pass ConfigurationOption.tostring
