### ISSUE TITLE
K8s operator don't start correctly

### ISSUE THREAD

**Issue by jakuboskera** [Xabaril/AspNetCore.Diagnostics.HealthChecks#843]
K8s operator don't start correctly. I deployed official YAML manifests without some changes (used tag `latest` so version `5.0.0` )to a two clusters:
- VMware Tanzu K8s cluster v1.20.6 (network policies enabled)
- local KIND K8s cluster v1.21.1 (network policies disabled)

From first cluster the error log is different from error log from second cluster. I thought that it can be a problem with network policies, so I created a network policy in first cluster which allow all communication within the namespace, but also without success.

Here are logs from a pod deployed in VMware Tanzu K8s cluster 1.20.6 (network policies enabled)
```console
[13:39:13 INF[] Starting Kubernetes client using host: https://10.100.200.1:443/
[13:39:13 INF[] The operator is starting
[13:40:54 ERR[] The operator threw an unhandled exception
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter[](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   at k8s.WatcherDelegatingHandler.CancelableStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadLineAsyncInternal()
   at k8s.WatcherDelegatingHandler.PeekableStreamReader.PeekLineAsync()
   at k8s.WatcherDelegatingHandler.LineSeparatedHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at k8s.Kubernetes.ListClusterCustomObjectWithHttpMessagesAsync(String group, String version, String plural, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at HealthChecks.UI.K8s.Operator.HealthChecksOperator.StartWatcher(CancellationToken token) in /src/src/HealthChecks.UI.K8s.Operator/Operator/HealthChecksOperator.cs:line 79
   at HealthChecks.UI.K8s.Operator.HealthChecksOperator.StartAsync(CancellationToken cancellationToken) in /src/src/HealthChecks.UI.K8s.Operator/Operator/HealthChecksOperator.cs:line 57
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at HealthChecks.UI.K8s.Operator.Program.Main(String[] args) in /src/src/HealthChecks.UI.K8s.Operator/Program.cs:line 25
```

Here are logs from a pod deployed in local KIND k8s cluster v1.21.1 (network policies disabled)
```console
[14:02:43 INF[] Starting Kubernetes client using host: https://10.96.0.1:443/
[14:02:43 INF[] The operator is starting
[14:02:43 ERR[] The operator threw an unhandled exception
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'
   at k8s.Kubernetes.ListClusterCustomObjectWithHttpMessagesAsync(String group, String version, String plural, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at HealthChecks.UI.K8s.Operator.HealthChecksOperator.StartWatcher(CancellationToken token) in /src/src/HealthChecks.UI.K8s.Operator/Operator/HealthChecksOperator.cs:line 79
   at HealthChecks.UI.K8s.Operator.HealthChecksOperator.StartAsync(CancellationToken cancellationToken) in /src/src/HealthChecks.UI.K8s.Operator/Operator/HealthChecksOperator.cs:line 57
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at HealthChecks.UI.K8s.Operator.Program.Main(String[] args) in /src/src/HealthChecks.UI.K8s.Operator/Program.cs:line 25
```

**Comment by jakuboskera** [comment]
some news?

**Comment by AleksuKey** [comment]
Same problem here...
