### ISSUE TITLE
.NET 6.0 Support / EF 5.0.1 fix

### ISSUE THREAD

**Issue by cculver** [Xabaril/AspNetCore.Diagnostics.HealthChecks#845]
It would be helpful to release a prerelease version of this library so we can start working with it on .NET 6.0. Currently, when trying to run from .NET 6, we run into a major problem with the UI in that upon initializing entities for Entity Framework Core 5.0.1, the application crashes. I'm asking to either upgrade everything to .NET 6 or to at least upgrade EF to 5.0.5 to fix that bug.

Please see https://github.com/dotnet/runtime/issues/49683 for the 5.0.1 problem / 5.0.5 fix under .NET 6.0.

**Comment by projectje** [comment]
I just wanted to doublecheck that probably then also falls under this:

```
System.TypeLoadException: Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'Microsoft.EntityFrameworkCore.InMemory, Version=5.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at Microsoft.EntityFrameworkCore.InMemory.Infrastructure.Internal.InMemoryOptionsExtension.get_Info()
   at Microsoft.EntityFrameworkCore.DbContextOptions.GetHashCode()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at HealthChecks.UI.Core.Data.HealthChecksDb..ctor(DbContextOptions`1 options)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at HealthChecks.UI.Core.HostedService.UIInitializationHostedService.InitializeDatabase(IServiceProvider sp)
   at HealthChecks.UI.Core.HostedService.UIInitializationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
```

**Comment by carlosrecuero** [comment]
Hi @projectje, thank you for your comment. Could you please provide me further information about how to reproduce this error?

**Comment by projectje** [comment]
@carlosrecuero  Hi, I register some healthchecks and add the endpoints, when i comment it out the application works fine.
Will check further

**Comment by alirezanet** [comment]
Any update on this ? .NET 6.0 is officially out.

**Comment by carlosrecuero** [comment]
Hi, thank you for your interest. There is already a preview version for net6.0.

**Comment by alirezanet** [comment]
> Hi, thank you for your interest. There is already a preview version for net6.0.
Thanks, but i can't find any preview version for the first three packages. 
```xml
      <PackageVersion Include="AspNetCore.HealthChecks.UI" Version="5.0.1"/>
      <PackageVersion Include="AspNetCore.HealthChecks.UI.Client" Version="5.0.1"/>
      <PackageVersion Include="AspNetCore.HealthChecks.UI.MySql.Storage" Version="5.0.1"/>

      <PackageVersion Include="AspNetCore.HealthChecks.MongoDb" Version="6.0.1-rc1.1"/>
      <PackageVersion Include="AspNetCore.HealthChecks.Redis" Version="6.0.1-rc1.1"/>
      <PackageVersion Include="AspNetCore.HealthChecks.MySql" Version="6.0.1-rc1.1"/>
      <PackageVersion Include="AspNetCore.HealthChecks.Network" Version="6.0.1-rc1.1"/>
      <PackageVersion Include="AspNetCore.HealthChecks.System" Version="6.0.1-rc1.1"/>
      <PackageVersion Include="AspNetCore.HealthChecks.Uris" Version="6.0.1" />
```

**Comment by ok10d** [comment]
Could't find a preview version of below for net 6.0.

```xml
<PackageReference Include="AspNetCore.HealthChecks.UI" Version="5.0.1" />
<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="5.0.1" />
<PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="5.0.1" />
```
Causes below on initialization:

```
[INF] [HealthChecks.UI.Core.HostedService.UIInitializationHostedService] Initializing UI Database
Unhandled exception. System.TypeInitializationException: The type initializer for 'Microsoft.EntityFrameworkCore.Query.QueryableMethods' threw an exception.
```

**Comment by unaizorrilla** [comment]
Nope, the UI is not deployed yet on 6.0 We are working on it!

**Comment by unaizorrilla** [comment]
Hi!

-rc2 version for .NET 6 already on NuGet, we hope to release final version ASAP!

**Comment by mathiasbl** [comment]
Can we get an rc version for AspNetCore.HealthChecks.AzureKeyVault and AspNetCore.HealthChecks.AzureStorage?

**Comment by carlosrecuero** [comment]
Yes, we are working on them. Quite likely, they will be ready at the end of the week.

**Comment by JuergenGutsch** [comment]
The preview version 6.0.1-rc2.4 is working with ASP.NET Core 6.0

**Comment by skoruba** [comment]
Hi, when do you plan to release stable version 6? Thanks!

**Comment by JuergenGutsch** [comment]
Yea, that would be great. The rc2.4 works quite well. This could be published as the final version from my point of view.

**Comment by carlosrecuero** [comment]
We are finishing it and will be ready in the following days.

**Comment by skoruba** [comment]
I can see that almost all packages are released, which is great 😊 Can you please release also UI packages? 

Thanks

**Comment by carlosrecuero** [comment]
Hi @skoruba, UI packages has been release now

**Comment by saddamhossain** [comment]
The UI is not working with .NET 7.0

**Comment by saddamhossain** [comment]
The UI is not working with .NET 7.0 
![error](https://user-images.githubusercontent.com/8841098/236598896-b26c7dc2-d663-4a52-9474-e88c363e998a.png)

**Comment by saddamhossain** [comment]
The UI is not working with .NET 7.0. I am using the following packages:

`
   <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="6.0.2" />
`
`
    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="6.0.5" />
`
`
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="6.0.5" />
`
`
    <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="6.0.5" />
`

This is the error I encountered: 

![error](https://user-images.githubusercontent.com/8841098/236598924-770690bc-821f-4b8c-b9ef-a4b93ff54568.png)

**Comment by sungam3r** [comment]
Try latest v7-preview packages, they support net7.
