### ISSUE TITLE
Xabari HealthCheck packages (for SQL Server, Hangfire) for Asp.NET Core 3.1 breaks the API

### ISSUE THREAD

**Issue by chathu03j** [Xabaril/AspNetCore.Diagnostics.HealthChecks#864]
I'm trying to configure healthchecks for my ASP.NET Core 3.1 microservices. I'm using the Xabari HealthCheck packages for SQL Server and Hangfire (both 3.1 versions) as per the documentation.

When I run the Web API on IIS Express on VS, the API works fine. However when I host on IIS (inprocess mode), I get the following error on the API:

`MissingMethodException: Method not found:
					&#x27;Microsoft.Extensions.DependencyInjection.IHealthChecksBuilder
					Microsoft.Extensions.DependencyInjection.SqlServerHealthCheckBuilderExtensions.AddSqlServer(Microsoft.Extensions.DependencyInjection.IHealthChecksBuilder,
					System.String, System.String, System.String,
					System.Nullable<Microsoft.Extensions.Diagnostics.HealthChecks.HealthStatus>
					System.Collections.Generic.IEnumerable
					System.Nullable<System.TimeSpan>;`

Following is a screenshot of the packages:
![image](https://user-images.githubusercontent.com/4024989/143242110-c7f98947-7eb0-45f2-b909-3b697423a9a3.png)

(Notice that I removed the Hangfire package to verify if it's causing the issue)

Stack trace is attached below:
```
Unhandled exception. System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IHealthChecksBuilder Microsoft.Extensions.DependencyInjection.SqlServerHealthCheckBuilderExtensions.AddSqlServer(Microsoft.Extensions.DependencyInjection.IHealthChecksBuilder, System.String, System.String, System.String, System.Nullable<Microsoft.Extensions.Diagnostics.HealthChecks.HealthStatus>, System.Collections.Generic.IEnumerable<System.String>, System.Nullable<System.TimeSpan>)

   at Administration.API.StartupExtensionMethods.RegisterHealthCheck(IServiceCollection services, IConfiguration Configuration)

   at Administration.API.Startup.ConfigureServices(IServiceCollection services) in D:\AdminAPI\Startup.cs:line 285

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)

   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)

   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)

   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)

   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)

   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)

   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()

   at Microsoft.Extensions.Hosting.HostBuilder.Build()

   at Administration.API.Program.Main() in D:\AdminAPI\Program.cs:line 24
```

Startup.cs
`services.AddHealthChecks()
               .AddCheck<ApiHealthCheck>("AdminAPI health check", null, new[] { "webapi", "microservice" })
               .AddCheck<SystemDbHealthCheck>("System Database health check", null, new[] { "database", "sql" });
               .AddSqlServer(connectionString: Configuration.GetValue<string>("ConnectionStrings:SystemDbConnectionString"),
                  healthQuery: "SELECT 1;",
                  name: "SQL Server: System DB",
                  failureStatus: HealthStatus.Degraded,
                  tags: new string[] { "db", "sql", "sqlserver" });`

**Comment by sungam3r** [comment]
Can you provide a stack trace of that exception ?

**Comment by chathu03j** [comment]
> Can you provide a stack trace of that exception ?

Updated the question with the stacktrace.

**Comment by sungam3r** [comment]
This error obviously occurs due to the mismatch of the versions of the assemblies used in compilation and deployment. The question is why they are different. Try to print all loaded assemblies with their versions when this error occures. Then do the same when API works fine under IIS Express and compare results.

I'm not familiar with IIS but I think that it's some sort of IIS configuration issue.

**Comment by chathu03j** [comment]
> This error obviously occurs due to the mismatch of the versions of the assemblies used in compilation and deployment. The question is why they are different. Try to print all loaded assemblies with their versions when this error occures. Then do the same when API works fine under IIS Express and compare results.
> 
> I'm not familiar with IIS but I think that it's some sort of IIS configuration issue.

Actually, I just figured out - this happens when I publish the binaries in debug configuration. I set it to release and there's no error any longer.
