### ISSUE TITLE
Health Checks UI crash on start .NET 6

### ISSUE THREAD

**Issue by serp777** [Xabaril/AspNetCore.Diagnostics.HealthChecks#868]
**What happened**:

Asp.net application doesn't start due to exception on Build().Run()

**What you expected to happen**:

I expected it to run past build and run on program.cs

**How to reproduce it (as minimally and precisely as possible)**:

.Net 6, create a simple example using:  services.AddHealthChecksUI().AddInMemoryStorage();

**Source code sample**:

Basic example on .net 6

**Anything else we need to know?**:

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.EntityFrameworkCore.Query.QueryableMethods' threw an exception.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.QueryableMethods.get_AnyWithoutPredicate()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AnyAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at HealthChecks.UI.Core.HostedService.UIInitializationHostedService.<InitializeDatabase>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at HealthChecks.UI.Core.HostedService.UIInitializationHostedService.<StartAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at XXXXX.Program.Main(String[] args) in C:\Users\XXXXX\source\repos\XXX\XXXXXXX\Program.cs:line 10

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidOperationException: Sequence contains more than one matching element

**Environment**:

- .NET Core version 6
- Healthchecks version Latest on nuget
- Operative system: Windows 10

**Comment by serp777** [comment]
Force installing entity framework and entity framework in memory cache package 5.0.12 solves the problem as  a workaround

**Comment by sungam3r** [comment]
.NET6 support is under progress in `netcore-6.0` branch.

**Comment by maxkoshevoi** [comment]
@sungam3r Is there any ETA on that? Or maybe some milestone that tracks the progress of net6 support?

**Comment by sungam3r** [comment]
I help here as collaborator. I do not have much time because there are other projects that require support. @carlosrecuero and @unaizorrilla know better about .NET6 ETA.

**Comment by carlosrecuero** [comment]
Hi @maxkoshevoi, there is already a preview release of HealthChecks for Net Core 6.0. Have you tried with these preview versions?

Soon, that preview version will be a stable one, but I cannot be more precise right now.

**Comment by maxkoshevoi** [comment]
Hi @carlosrecuero, thanks for the reply. Preview works fine, was just wondering when stable version could be available, so I could use it in production.

**Comment by Uffman** [comment]
> Hi @carlosrecuero, thanks for the reply. Preview works fine, was just wondering when stable version could be available, so I could use it in production.

I am also waiting for a stable version.

**Comment by maxkoshevoi** [comment]
It's released! 🎉
